// Code generated by Fern. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersByIDIncludeDeletedDomainsRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug", func(t *testing.T) {
		obj := &ByIDIncludeDeletedDomainsRequest{}
		var fernTestValueWorkspaceSlug string
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)
		assert.Equal(t, fernTestValueWorkspaceSlug, obj.WorkspaceSlug)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetArgs", func(t *testing.T) {
		obj := &ByIDIncludeDeletedDomainsRequest{}
		var fernTestValueArgs *ByIDIncludeDeletedDomainsRequestArgs
		obj.SetArgs(fernTestValueArgs)
		assert.Equal(t, fernTestValueArgs, obj.Args)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitByIDIncludeDeletedDomainsRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ByIDIncludeDeletedDomainsRequest{}
		var fernTestValueWorkspaceSlug string

		// Act
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetArgs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ByIDIncludeDeletedDomainsRequest{}
		var fernTestValueArgs *ByIDIncludeDeletedDomainsRequestArgs

		// Act
		obj.SetArgs(fernTestValueArgs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueType *string
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueStatus *QueryDomainsByIDIncludeDeletedResponseStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDeletedAt", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueDeletedAt *float64
		obj.SetDeletedAt(fernTestValueDeletedAt)
		assert.Equal(t, fernTestValueDeletedAt, obj.DeletedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainMetadata", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueDomainMetadata *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		obj.SetDomainMetadata(fernTestValueDomainMetadata)
		assert.Equal(t, fernTestValueDomainMetadata, obj.DomainMetadata)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var expected *string
		obj.Type = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetType(), "getter should return the property value")
	})

	t.Run("GetType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		obj.Type = nil

		// Act & Assert
		assert.Nil(t, obj.GetType(), "getter should return nil when property is nil")
	})

	t.Run("GetType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetType() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var expected *QueryDomainsByIDIncludeDeletedResponseStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		obj.Status = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetDeletedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var expected *float64
		obj.DeletedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDeletedAt(), "getter should return the property value")
	})

	t.Run("GetDeletedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		obj.DeletedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetDeletedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetDeletedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDeletedAt() // Should return zero value
	})

	t.Run("GetDomainMetadata", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var expected *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		obj.DomainMetadata = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainMetadata(), "getter should return the property value")
	})

	t.Run("GetDomainMetadata_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		obj.DomainMetadata = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainMetadata(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainMetadata_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainMetadata() // Should return zero value
	})

}

func TestSettersMarkExplicitQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueType *string

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueStatus *QueryDomainsByIDIncludeDeletedResponseStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDeletedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueDeletedAt *float64

		// Act
		obj.SetDeletedAt(fernTestValueDeletedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainMetadata_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		var fernTestValueDomainMetadata *QueryDomainsByIDIncludeDeletedResponseDomainMetadata

		// Act
		obj.SetDomainMetadata(fernTestValueDomainMetadata)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	t.Run("SetCfHostnameID", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueCfHostnameID string
		obj.SetCfHostnameID(fernTestValueCfHostnameID)
		assert.Equal(t, fernTestValueCfHostnameID, obj.CfHostnameID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCfSslStatus", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueCfSslStatus *string
		obj.SetCfSslStatus(fernTestValueCfSslStatus)
		assert.Equal(t, fernTestValueCfSslStatus, obj.CfSslStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastError", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueLastError *string
		obj.SetLastError(fernTestValueLastError)
		assert.Equal(t, fernTestValueLastError, obj.LastError)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueProvider *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	t.Run("GetCfHostnameID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var expected string
		obj.CfHostnameID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCfHostnameID(), "getter should return the property value")
	})

	t.Run("GetCfHostnameID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCfHostnameID() // Should return zero value
	})

	t.Run("GetCfSslStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var expected *string
		obj.CfSslStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCfSslStatus(), "getter should return the property value")
	})

	t.Run("GetCfSslStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		obj.CfSslStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetCfSslStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetCfSslStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCfSslStatus() // Should return zero value
	})

	t.Run("GetLastError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var expected *string
		obj.LastError = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastError(), "getter should return the property value")
	})

	t.Run("GetLastError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		obj.LastError = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastError(), "getter should return nil when property is nil")
	})

	t.Run("GetLastError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastError() // Should return zero value
	})

	t.Run("GetProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var expected *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider
		obj.Provider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProvider(), "getter should return the property value")
	})

	t.Run("GetProvider_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		obj.Provider = nil

		// Act & Assert
		assert.Nil(t, obj.GetProvider(), "getter should return nil when property is nil")
	})

	t.Run("GetProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProvider() // Should return zero value
	})

}

func TestSettersMarkExplicitQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	t.Run("SetCfHostnameID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueCfHostnameID string

		// Act
		obj.SetCfHostnameID(fernTestValueCfHostnameID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCfSslStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueCfSslStatus *string

		// Act
		obj.SetCfSslStatus(fernTestValueCfSslStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueLastError *string

		// Act
		obj.SetLastError(fernTestValueLastError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		var fernTestValueProvider *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersByIDIncludeDeletedDomainsRequestArgs(t *testing.T) {
	t.Run("SetDomainID", func(t *testing.T) {
		obj := &ByIDIncludeDeletedDomainsRequestArgs{}
		var fernTestValueDomainID string
		obj.SetDomainID(fernTestValueDomainID)
		assert.Equal(t, fernTestValueDomainID, obj.DomainID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersByIDIncludeDeletedDomainsRequestArgs(t *testing.T) {
	t.Run("GetDomainID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ByIDIncludeDeletedDomainsRequestArgs{}
		var expected string
		obj.DomainID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainID(), "getter should return the property value")
	})

	t.Run("GetDomainID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ByIDIncludeDeletedDomainsRequestArgs
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainID() // Should return zero value
	})

}

func TestSettersMarkExplicitByIDIncludeDeletedDomainsRequestArgs(t *testing.T) {
	t.Run("SetDomainID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ByIDIncludeDeletedDomainsRequestArgs{}
		var fernTestValueDomainID string

		// Act
		obj.SetDomainID(fernTestValueDomainID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingByIDIncludeDeletedDomainsRequestArgs(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ByIDIncludeDeletedDomainsRequestArgs{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ByIDIncludeDeletedDomainsRequestArgs
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ByIDIncludeDeletedDomainsRequestArgs
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ByIDIncludeDeletedDomainsRequestArgs
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled QueryDomainsByIDIncludeDeletedResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestRequiredNullableRoundTripQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	requiredNullableKeys := []string{
		"type",
		"status",
		"deletedAt",
		"domainMetadata",
	}
	marshalToMap := func(t *testing.T, obj *QueryDomainsByIDIncludeDeletedResponse) map[string]json.RawMessage {
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		var result map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(data, &result), "marshaled data should be a JSON object")
		return result
	}

	t.Run("NullPreserved", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponse
		require.NoError(t, json.Unmarshal([]byte(`{"type":null,"status":null,"deletedAt":null,"domainMetadata":null}`), &obj))
		result := marshalToMap(t, &obj)
		for _, key := range requiredNullableKeys {
			value, ok := result[key]
			require.True(t, ok, "required nullable field %q received as null should be present in the output", key)
			assert.Equal(t, "null", string(value), "required nullable field %q received as null should be null in the output", key)
		}
	})

	t.Run("AbsentStaysAbsent", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponse
		require.NoError(t, json.Unmarshal([]byte(`{}`), &obj))
		result := marshalToMap(t, &obj)
		for _, key := range requiredNullableKeys {
			assert.NotContains(t, result, key, "required nullable field %q absent from the input should be absent from the output", key)
		}
	})

	t.Run("FreshValueOmits", func(t *testing.T) {
		t.Parallel()
		result := marshalToMap(t, &QueryDomainsByIDIncludeDeletedResponse{})
		for _, key := range requiredNullableKeys {
			assert.NotContains(t, result, key, "required nullable field %q should be omitted from a freshly constructed value", key)
		}
	})
}

func TestOptionalNullableRoundTripQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	optionalNullableKeys := []string{
		"cfSslStatus",
		"lastError",
	}
	marshalToMap := func(t *testing.T, obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) map[string]json.RawMessage {
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		var result map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(data, &result), "marshaled data should be a JSON object")
		return result
	}

	t.Run("NullPreserved", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		require.NoError(t, json.Unmarshal([]byte(`{"cfSslStatus":null,"lastError":null}`), &obj))
		result := marshalToMap(t, &obj)
		for _, key := range optionalNullableKeys {
			value, ok := result[key]
			require.True(t, ok, "optional nullable field %q received as null should be present in the output", key)
			assert.Equal(t, "null", string(value), "optional nullable field %q received as null should be null in the output", key)
		}
	})

	t.Run("AbsentStaysAbsent", func(t *testing.T) {
		t.Parallel()
		var obj QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		require.NoError(t, json.Unmarshal([]byte(`{}`), &obj))
		result := marshalToMap(t, &obj)
		for _, key := range optionalNullableKeys {
			assert.NotContains(t, result, key, "optional nullable field %q absent from the input should be absent from the output", key)
		}
	})

	t.Run("FreshValueOmits", func(t *testing.T) {
		t.Parallel()
		result := marshalToMap(t, &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{})
		for _, key := range optionalNullableKeys {
			assert.NotContains(t, result, key, "optional nullable field %q should be omitted from a freshly constructed value", key)
		}
	})
}

func TestStringByIDIncludeDeletedDomainsRequestArgs(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ByIDIncludeDeletedDomainsRequestArgs{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ByIDIncludeDeletedDomainsRequestArgs
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumQueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider(t *testing.T) {
	t.Run("NewFromString_cloudflare", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("cloudflare")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("cloudflare"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_aws", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("aws")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("aws"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_vercel", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("vercel")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("vercel"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_godaddy", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("godaddy")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("godaddy"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_namecheap", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("namecheap")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("namecheap"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_squarespace", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("squarespace")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("squarespace"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_google_cloud", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("google-cloud")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("google-cloud"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_generic", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("generic")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider("generic"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString("cloudflare")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumQueryDomainsByIDIncludeDeletedResponseStatus(t *testing.T) {
	t.Run("NewFromString_pending", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseStatusFromString("pending")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseStatus("pending"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_active", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseStatusFromString("active")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseStatus("active"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseStatusFromString("failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseStatus("failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_requires_reactivation", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDomainsByIDIncludeDeletedResponseStatusFromString("requires_reactivation")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDomainsByIDIncludeDeletedResponseStatus("requires_reactivation"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewQueryDomainsByIDIncludeDeletedResponseStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewQueryDomainsByIDIncludeDeletedResponseStatusFromString("pending")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesByIDIncludeDeletedDomainsRequestArgs(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ByIDIncludeDeletedDomainsRequestArgs{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ByIDIncludeDeletedDomainsRequestArgs
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesQueryDomainsByIDIncludeDeletedResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &QueryDomainsByIDIncludeDeletedResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesQueryDomainsByIDIncludeDeletedResponseDomainMetadata(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &QueryDomainsByIDIncludeDeletedResponseDomainMetadata{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *QueryDomainsByIDIncludeDeletedResponseDomainMetadata
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
