// Code generated by Fern. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	byIDIncludeDeletedDomainsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	byIDIncludeDeletedDomainsRequestFieldArgs          = big.NewInt(1 << 1)
)

type ByIDIncludeDeletedDomainsRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string                                `json:"-" url:"-"`
	Args          *ByIDIncludeDeletedDomainsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByIDIncludeDeletedDomainsRequest) require(field *big.Int) {
	next := new(big.Int)
	if b.explicitFields != nil {
		next.Set(b.explicitFields)
	}
	next.Or(next, field)
	b.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByIDIncludeDeletedDomainsRequest) SetWorkspaceSlug(workspaceSlug string) {
	b.WorkspaceSlug = workspaceSlug
	b.require(byIDIncludeDeletedDomainsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByIDIncludeDeletedDomainsRequest) SetArgs(args *ByIDIncludeDeletedDomainsRequestArgs) {
	b.Args = args
	b.require(byIDIncludeDeletedDomainsRequestFieldArgs)
}

func (b *ByIDIncludeDeletedDomainsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ByIDIncludeDeletedDomainsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = ByIDIncludeDeletedDomainsRequest(body)
	return nil
}

func (b *ByIDIncludeDeletedDomainsRequest) MarshalJSON() ([]byte, error) {
	type embed ByIDIncludeDeletedDomainsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	queryDomainsByIDIncludeDeletedResponseFieldID             = big.NewInt(1 << 0)
	queryDomainsByIDIncludeDeletedResponseFieldName           = big.NewInt(1 << 1)
	queryDomainsByIDIncludeDeletedResponseFieldType           = big.NewInt(1 << 2)
	queryDomainsByIDIncludeDeletedResponseFieldStatus         = big.NewInt(1 << 3)
	queryDomainsByIDIncludeDeletedResponseFieldDeletedAt      = big.NewInt(1 << 4)
	queryDomainsByIDIncludeDeletedResponseFieldDomainMetadata = big.NewInt(1 << 5)
)

// queryDomainsByIDIncludeDeletedResponseNullableFields maps the wire names of QueryDomainsByIDIncludeDeletedResponse's nullable fields (required or optional) to their field bits.
var queryDomainsByIDIncludeDeletedResponseNullableFields = map[string]*big.Int{
	"type":           queryDomainsByIDIncludeDeletedResponseFieldType,
	"status":         queryDomainsByIDIncludeDeletedResponseFieldStatus,
	"deletedAt":      queryDomainsByIDIncludeDeletedResponseFieldDeletedAt,
	"domainMetadata": queryDomainsByIDIncludeDeletedResponseFieldDomainMetadata,
}

type QueryDomainsByIDIncludeDeletedResponse struct {
	// Unique tracking domain identifier.
	ID string `json:"id" url:"id"`
	// Lowercase fully qualified tracking hostname, without a trailing dot.
	Name string  `json:"name" url:"name"`
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Current hostname verification status.
	Status         *QueryDomainsByIDIncludeDeletedResponseStatus         `json:"status,omitempty" url:"status,omitempty"`
	DeletedAt      *float64                                              `json:"deletedAt,omitempty" url:"deletedAt,omitempty"`
	DomainMetadata *QueryDomainsByIDIncludeDeletedResponseDomainMetadata `json:"domainMetadata,omitempty" url:"domainMetadata,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetID() string {
	if q == nil {
		return ""
	}
	return q.ID
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetName() string {
	if q == nil {
		return ""
	}
	return q.Name
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetType() *string {
	if q == nil {
		return nil
	}
	return q.Type
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetStatus() *QueryDomainsByIDIncludeDeletedResponseStatus {
	if q == nil {
		return nil
	}
	return q.Status
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetDeletedAt() *float64 {
	if q == nil {
		return nil
	}
	return q.DeletedAt
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetDomainMetadata() *QueryDomainsByIDIncludeDeletedResponseDomainMetadata {
	if q == nil {
		return nil
	}
	return q.DomainMetadata
}

func (q *QueryDomainsByIDIncludeDeletedResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QueryDomainsByIDIncludeDeletedResponse) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponse) SetID(id string) {
	q.ID = id
	q.require(queryDomainsByIDIncludeDeletedResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponse) SetName(name string) {
	q.Name = name
	q.require(queryDomainsByIDIncludeDeletedResponseFieldName)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponse) SetType(type_ *string) {
	q.Type = type_
	q.require(queryDomainsByIDIncludeDeletedResponseFieldType)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponse) SetStatus(status *QueryDomainsByIDIncludeDeletedResponseStatus) {
	q.Status = status
	q.require(queryDomainsByIDIncludeDeletedResponseFieldStatus)
}

// SetDeletedAt sets the DeletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponse) SetDeletedAt(deletedAt *float64) {
	q.DeletedAt = deletedAt
	q.require(queryDomainsByIDIncludeDeletedResponseFieldDeletedAt)
}

// SetDomainMetadata sets the DomainMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponse) SetDomainMetadata(domainMetadata *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) {
	q.DomainMetadata = domainMetadata
	q.require(queryDomainsByIDIncludeDeletedResponseFieldDomainMetadata)
}

func (q *QueryDomainsByIDIncludeDeletedResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler QueryDomainsByIDIncludeDeletedResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QueryDomainsByIDIncludeDeletedResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, queryDomainsByIDIncludeDeletedResponseNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		q.require(presentFields)
	}
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueryDomainsByIDIncludeDeletedResponse) MarshalJSON() ([]byte, error) {
	type embed QueryDomainsByIDIncludeDeletedResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QueryDomainsByIDIncludeDeletedResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldCfHostnameID = big.NewInt(1 << 0)
	queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldCfSslStatus  = big.NewInt(1 << 1)
	queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldLastError    = big.NewInt(1 << 2)
	queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldProvider     = big.NewInt(1 << 3)
)

// queryDomainsByIDIncludeDeletedResponseDomainMetadataNullableFields maps the wire names of QueryDomainsByIDIncludeDeletedResponseDomainMetadata's nullable fields (required or optional) to their field bits.
var queryDomainsByIDIncludeDeletedResponseDomainMetadataNullableFields = map[string]*big.Int{
	"cfSslStatus": queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldCfSslStatus,
	"lastError":   queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldLastError,
}

type QueryDomainsByIDIncludeDeletedResponseDomainMetadata struct {
	CfHostnameID string `json:"cfHostnameId" url:"cfHostnameId"`
	// Current TLS certificate provisioning status.
	CfSslStatus *string                                                       `json:"cfSslStatus,omitempty" url:"cfSslStatus,omitempty"`
	LastError   *string                                                       `json:"lastError,omitempty" url:"lastError,omitempty"`
	Provider    *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider `json:"provider,omitempty" url:"provider,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) GetCfHostnameID() string {
	if q == nil {
		return ""
	}
	return q.CfHostnameID
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) GetCfSslStatus() *string {
	if q == nil {
		return nil
	}
	return q.CfSslStatus
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) GetLastError() *string {
	if q == nil {
		return nil
	}
	return q.LastError
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) GetProvider() *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider {
	if q == nil {
		return nil
	}
	return q.Provider
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetCfHostnameID sets the CfHostnameID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) SetCfHostnameID(cfHostnameID string) {
	q.CfHostnameID = cfHostnameID
	q.require(queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldCfHostnameID)
}

// SetCfSslStatus sets the CfSslStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) SetCfSslStatus(cfSslStatus *string) {
	q.CfSslStatus = cfSslStatus
	q.require(queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldCfSslStatus)
}

// SetLastError sets the LastError field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) SetLastError(lastError *string) {
	q.LastError = lastError
	q.require(queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldLastError)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) SetProvider(provider *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider) {
	q.Provider = provider
	q.require(queryDomainsByIDIncludeDeletedResponseDomainMetadataFieldProvider)
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) UnmarshalJSON(data []byte) error {
	type unmarshaler QueryDomainsByIDIncludeDeletedResponseDomainMetadata
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QueryDomainsByIDIncludeDeletedResponseDomainMetadata(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, queryDomainsByIDIncludeDeletedResponseDomainMetadataNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		q.require(presentFields)
	}
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) MarshalJSON() ([]byte, error) {
	type embed QueryDomainsByIDIncludeDeletedResponseDomainMetadata
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QueryDomainsByIDIncludeDeletedResponseDomainMetadata) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

type QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider string

const (
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderCloudflare  QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "cloudflare"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderAws         QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "aws"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderVercel      QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "vercel"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderGodaddy     QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "godaddy"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderNamecheap   QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "namecheap"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderSquarespace QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "squarespace"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderGoogleCloud QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "google-cloud"
	QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderGeneric     QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider = "generic"
)

func NewQueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderFromString(s string) (QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider, error) {
	switch s {
	case "cloudflare":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderCloudflare, nil
	case "aws":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderAws, nil
	case "vercel":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderVercel, nil
	case "godaddy":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderGodaddy, nil
	case "namecheap":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderNamecheap, nil
	case "squarespace":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderSquarespace, nil
	case "google-cloud":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderGoogleCloud, nil
	case "generic":
		return QueryDomainsByIDIncludeDeletedResponseDomainMetadataProviderGeneric, nil
	}
	var t QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider) Ptr() *QueryDomainsByIDIncludeDeletedResponseDomainMetadataProvider {
	return &q
}

// Current hostname verification status.
type QueryDomainsByIDIncludeDeletedResponseStatus string

const (
	QueryDomainsByIDIncludeDeletedResponseStatusPending              QueryDomainsByIDIncludeDeletedResponseStatus = "pending"
	QueryDomainsByIDIncludeDeletedResponseStatusActive               QueryDomainsByIDIncludeDeletedResponseStatus = "active"
	QueryDomainsByIDIncludeDeletedResponseStatusFailed               QueryDomainsByIDIncludeDeletedResponseStatus = "failed"
	QueryDomainsByIDIncludeDeletedResponseStatusRequiresReactivation QueryDomainsByIDIncludeDeletedResponseStatus = "requires_reactivation"
)

func NewQueryDomainsByIDIncludeDeletedResponseStatusFromString(s string) (QueryDomainsByIDIncludeDeletedResponseStatus, error) {
	switch s {
	case "pending":
		return QueryDomainsByIDIncludeDeletedResponseStatusPending, nil
	case "active":
		return QueryDomainsByIDIncludeDeletedResponseStatusActive, nil
	case "failed":
		return QueryDomainsByIDIncludeDeletedResponseStatusFailed, nil
	case "requires_reactivation":
		return QueryDomainsByIDIncludeDeletedResponseStatusRequiresReactivation, nil
	}
	var t QueryDomainsByIDIncludeDeletedResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryDomainsByIDIncludeDeletedResponseStatus) Ptr() *QueryDomainsByIDIncludeDeletedResponseStatus {
	return &q
}

var (
	byIDIncludeDeletedDomainsRequestArgsFieldDomainID = big.NewInt(1 << 0)
)

type ByIDIncludeDeletedDomainsRequestArgs struct {
	DomainID string `json:"domainId" url:"domainId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByIDIncludeDeletedDomainsRequestArgs) GetDomainID() string {
	if b == nil {
		return ""
	}
	return b.DomainID
}

func (b *ByIDIncludeDeletedDomainsRequestArgs) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByIDIncludeDeletedDomainsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if b.explicitFields != nil {
		next.Set(b.explicitFields)
	}
	next.Or(next, field)
	b.explicitFields = next
}

// SetDomainID sets the DomainID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByIDIncludeDeletedDomainsRequestArgs) SetDomainID(domainID string) {
	b.DomainID = domainID
	b.require(byIDIncludeDeletedDomainsRequestArgsFieldDomainID)
}

func (b *ByIDIncludeDeletedDomainsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler ByIDIncludeDeletedDomainsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByIDIncludeDeletedDomainsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByIDIncludeDeletedDomainsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed ByIDIncludeDeletedDomainsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByIDIncludeDeletedDomainsRequestArgs) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}
