// Code generated by Fern. DO NOT EDIT.

package sdk

import (
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
)


var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
    400: func(apiError *core.APIError) error{
        return &BadRequestError{
            APIError: apiError,
        }
    },
    401: func(apiError *core.APIError) error{
        return &UnauthorizedError{
            APIError: apiError,
        }
    },
    403: func(apiError *core.APIError) error{
        return &ForbiddenError{
            APIError: apiError,
        }
    },
    503: func(apiError *core.APIError) error{
        return &ServiceUnavailableError{
            APIError: apiError,
        }
    },
    409: func(apiError *core.APIError) error{
        return &ConflictError{
            APIError: apiError,
        }
    },
    404: func(apiError *core.APIError) error{
        return &NotFoundError{
            APIError: apiError,
        }
    },
}

