// Code generated by Fern. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	installationsIntegrationsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	installationsIntegrationsRequestFieldArgs          = big.NewInt(1 << 1)
)

type InstallationsIntegrationsRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string                                `json:"-" url:"-"`
	Args          *InstallationsIntegrationsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallationsIntegrationsRequest) require(field *big.Int) {
	next := new(big.Int)
	if i.explicitFields != nil {
		next.Set(i.explicitFields)
	}
	next.Or(next, field)
	i.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallationsIntegrationsRequest) SetWorkspaceSlug(workspaceSlug string) {
	i.WorkspaceSlug = workspaceSlug
	i.require(installationsIntegrationsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallationsIntegrationsRequest) SetArgs(args *InstallationsIntegrationsRequestArgs) {
	i.Args = args
	i.require(installationsIntegrationsRequestFieldArgs)
}

func (i *InstallationsIntegrationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InstallationsIntegrationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = InstallationsIntegrationsRequest(body)
	return nil
}

func (i *InstallationsIntegrationsRequest) MarshalJSON() ([]byte, error) {
	type embed InstallationsIntegrationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	linkSurfaceToDestinationIntegrationsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	linkSurfaceToDestinationIntegrationsRequestFieldArgs          = big.NewInt(1 << 1)
)

type LinkSurfaceToDestinationIntegrationsRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string                                           `json:"-" url:"-"`
	Args          *LinkSurfaceToDestinationIntegrationsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LinkSurfaceToDestinationIntegrationsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToDestinationIntegrationsRequest) SetWorkspaceSlug(workspaceSlug string) {
	l.WorkspaceSlug = workspaceSlug
	l.require(linkSurfaceToDestinationIntegrationsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToDestinationIntegrationsRequest) SetArgs(args *LinkSurfaceToDestinationIntegrationsRequestArgs) {
	l.Args = args
	l.require(linkSurfaceToDestinationIntegrationsRequestFieldArgs)
}

func (l *LinkSurfaceToDestinationIntegrationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkSurfaceToDestinationIntegrationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = LinkSurfaceToDestinationIntegrationsRequest(body)
	return nil
}

func (l *LinkSurfaceToDestinationIntegrationsRequest) MarshalJSON() ([]byte, error) {
	type embed LinkSurfaceToDestinationIntegrationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	linkSurfaceToRepositoryIntegrationsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	linkSurfaceToRepositoryIntegrationsRequestFieldArgs          = big.NewInt(1 << 1)
)

type LinkSurfaceToRepositoryIntegrationsRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string                                          `json:"-" url:"-"`
	Args          *LinkSurfaceToRepositoryIntegrationsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LinkSurfaceToRepositoryIntegrationsRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToRepositoryIntegrationsRequest) SetWorkspaceSlug(workspaceSlug string) {
	l.WorkspaceSlug = workspaceSlug
	l.require(linkSurfaceToRepositoryIntegrationsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToRepositoryIntegrationsRequest) SetArgs(args *LinkSurfaceToRepositoryIntegrationsRequestArgs) {
	l.Args = args
	l.require(linkSurfaceToRepositoryIntegrationsRequestFieldArgs)
}

func (l *LinkSurfaceToRepositoryIntegrationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkSurfaceToRepositoryIntegrationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = LinkSurfaceToRepositoryIntegrationsRequest(body)
	return nil
}

func (l *LinkSurfaceToRepositoryIntegrationsRequest) MarshalJSON() ([]byte, error) {
	type embed LinkSurfaceToRepositoryIntegrationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mutationIntegrationsLinkSurfaceToDestinationResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationIntegrationsLinkSurfaceToDestinationResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationIntegrationsLinkSurfaceToDestinationResponseFieldSuccess)
}

func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationIntegrationsLinkSurfaceToDestinationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationIntegrationsLinkSurfaceToDestinationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) MarshalJSON() ([]byte, error) {
	type embed MutationIntegrationsLinkSurfaceToDestinationResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationIntegrationsLinkSurfaceToDestinationResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationIntegrationsLinkSurfaceToRepositoryResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationIntegrationsLinkSurfaceToRepositoryResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationIntegrationsLinkSurfaceToRepositoryResponseFieldSuccess)
}

func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationIntegrationsLinkSurfaceToRepositoryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationIntegrationsLinkSurfaceToRepositoryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) MarshalJSON() ([]byte, error) {
	type embed MutationIntegrationsLinkSurfaceToRepositoryResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationIntegrationsLinkSurfaceToRepositoryResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationIntegrationsUnlinkSurfaceDestinationMappingResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationIntegrationsUnlinkSurfaceDestinationMappingResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationIntegrationsUnlinkSurfaceDestinationMappingResponseFieldSuccess)
}

func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationIntegrationsUnlinkSurfaceDestinationMappingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationIntegrationsUnlinkSurfaceDestinationMappingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) MarshalJSON() ([]byte, error) {
	type embed MutationIntegrationsUnlinkSurfaceDestinationMappingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationIntegrationsUnlinkSurfaceDestinationMappingResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationIntegrationsUnlinkSurfaceMappingResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationIntegrationsUnlinkSurfaceMappingResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationIntegrationsUnlinkSurfaceMappingResponseFieldSuccess)
}

func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationIntegrationsUnlinkSurfaceMappingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationIntegrationsUnlinkSurfaceMappingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) MarshalJSON() ([]byte, error) {
	type embed MutationIntegrationsUnlinkSurfaceMappingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationIntegrationsUnlinkSurfaceMappingResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type QueryIntegrationsInstallationsResponse = []*QueryIntegrationsInstallationsResponseItem

var (
	queryIntegrationsInstallationsResponseItemFieldID       = big.NewInt(1 << 0)
	queryIntegrationsInstallationsResponseItemFieldProvider = big.NewInt(1 << 1)
	queryIntegrationsInstallationsResponseItemFieldStatus   = big.NewInt(1 << 2)
)

type QueryIntegrationsInstallationsResponseItem struct {
	// Unique integration installation identifier.
	ID string `json:"id" url:"id"`
	// Installed integration provider.
	Provider QueryIntegrationsInstallationsResponseItemProvider `json:"provider" url:"provider"`
	// Current integration installation status.
	Status string `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (q *QueryIntegrationsInstallationsResponseItem) GetID() string {
	if q == nil {
		return ""
	}
	return q.ID
}

func (q *QueryIntegrationsInstallationsResponseItem) GetProvider() QueryIntegrationsInstallationsResponseItemProvider {
	if q == nil {
		return ""
	}
	return q.Provider
}

func (q *QueryIntegrationsInstallationsResponseItem) GetStatus() string {
	if q == nil {
		return ""
	}
	return q.Status
}

func (q *QueryIntegrationsInstallationsResponseItem) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.ExtraProperties
}

func (q *QueryIntegrationsInstallationsResponseItem) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryIntegrationsInstallationsResponseItem) SetID(id string) {
	q.ID = id
	q.require(queryIntegrationsInstallationsResponseItemFieldID)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryIntegrationsInstallationsResponseItem) SetProvider(provider QueryIntegrationsInstallationsResponseItemProvider) {
	q.Provider = provider
	q.require(queryIntegrationsInstallationsResponseItemFieldProvider)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryIntegrationsInstallationsResponseItem) SetStatus(status string) {
	q.Status = status
	q.require(queryIntegrationsInstallationsResponseItemFieldStatus)
}

func (q *QueryIntegrationsInstallationsResponseItem) UnmarshalJSON(data []byte) error {
	type embed QueryIntegrationsInstallationsResponseItem
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QueryIntegrationsInstallationsResponseItem(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.ExtraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueryIntegrationsInstallationsResponseItem) MarshalJSON() ([]byte, error) {
	type embed QueryIntegrationsInstallationsResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, q.ExtraProperties)
}

func (q *QueryIntegrationsInstallationsResponseItem) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

// Installed integration provider.
type QueryIntegrationsInstallationsResponseItemProvider string

const (
	QueryIntegrationsInstallationsResponseItemProviderGithub     QueryIntegrationsInstallationsResponseItemProvider = "github"
	QueryIntegrationsInstallationsResponseItemProviderGheCloud   QueryIntegrationsInstallationsResponseItemProvider = "ghe_cloud"
	QueryIntegrationsInstallationsResponseItemProviderGheServer  QueryIntegrationsInstallationsResponseItemProvider = "ghe_server"
	QueryIntegrationsInstallationsResponseItemProviderVercel     QueryIntegrationsInstallationsResponseItemProvider = "vercel"
	QueryIntegrationsInstallationsResponseItemProviderCloudflare QueryIntegrationsInstallationsResponseItemProvider = "cloudflare"
	QueryIntegrationsInstallationsResponseItemProviderSlack      QueryIntegrationsInstallationsResponseItemProvider = "slack"
	QueryIntegrationsInstallationsResponseItemProviderCli        QueryIntegrationsInstallationsResponseItemProvider = "cli"
)

func NewQueryIntegrationsInstallationsResponseItemProviderFromString(s string) (QueryIntegrationsInstallationsResponseItemProvider, error) {
	switch s {
	case "github":
		return QueryIntegrationsInstallationsResponseItemProviderGithub, nil
	case "ghe_cloud":
		return QueryIntegrationsInstallationsResponseItemProviderGheCloud, nil
	case "ghe_server":
		return QueryIntegrationsInstallationsResponseItemProviderGheServer, nil
	case "vercel":
		return QueryIntegrationsInstallationsResponseItemProviderVercel, nil
	case "cloudflare":
		return QueryIntegrationsInstallationsResponseItemProviderCloudflare, nil
	case "slack":
		return QueryIntegrationsInstallationsResponseItemProviderSlack, nil
	case "cli":
		return QueryIntegrationsInstallationsResponseItemProviderCli, nil
	}
	var t QueryIntegrationsInstallationsResponseItemProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryIntegrationsInstallationsResponseItemProvider) Ptr() *QueryIntegrationsInstallationsResponseItemProvider {
	return &q
}

var (
	installationsIntegrationsRequestArgsFieldProviders = big.NewInt(1 << 0)
)

type InstallationsIntegrationsRequestArgs struct {
	Providers []InstallationsIntegrationsRequestArgsProvidersItem `json:"providers" url:"providers"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InstallationsIntegrationsRequestArgs) GetProviders() []InstallationsIntegrationsRequestArgsProvidersItem {
	if i == nil {
		return nil
	}
	return i.Providers
}

func (i *InstallationsIntegrationsRequestArgs) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InstallationsIntegrationsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if i.explicitFields != nil {
		next.Set(i.explicitFields)
	}
	next.Or(next, field)
	i.explicitFields = next
}

// SetProviders sets the Providers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallationsIntegrationsRequestArgs) SetProviders(providers []InstallationsIntegrationsRequestArgsProvidersItem) {
	i.Providers = providers
	i.require(installationsIntegrationsRequestArgsFieldProviders)
}

func (i *InstallationsIntegrationsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler InstallationsIntegrationsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InstallationsIntegrationsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InstallationsIntegrationsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed InstallationsIntegrationsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InstallationsIntegrationsRequestArgs) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InstallationsIntegrationsRequestArgsProvidersItem string

const (
	InstallationsIntegrationsRequestArgsProvidersItemGithub     InstallationsIntegrationsRequestArgsProvidersItem = "github"
	InstallationsIntegrationsRequestArgsProvidersItemGheCloud   InstallationsIntegrationsRequestArgsProvidersItem = "ghe_cloud"
	InstallationsIntegrationsRequestArgsProvidersItemGheServer  InstallationsIntegrationsRequestArgsProvidersItem = "ghe_server"
	InstallationsIntegrationsRequestArgsProvidersItemVercel     InstallationsIntegrationsRequestArgsProvidersItem = "vercel"
	InstallationsIntegrationsRequestArgsProvidersItemCloudflare InstallationsIntegrationsRequestArgsProvidersItem = "cloudflare"
	InstallationsIntegrationsRequestArgsProvidersItemSlack      InstallationsIntegrationsRequestArgsProvidersItem = "slack"
	InstallationsIntegrationsRequestArgsProvidersItemCli        InstallationsIntegrationsRequestArgsProvidersItem = "cli"
)

func NewInstallationsIntegrationsRequestArgsProvidersItemFromString(s string) (InstallationsIntegrationsRequestArgsProvidersItem, error) {
	switch s {
	case "github":
		return InstallationsIntegrationsRequestArgsProvidersItemGithub, nil
	case "ghe_cloud":
		return InstallationsIntegrationsRequestArgsProvidersItemGheCloud, nil
	case "ghe_server":
		return InstallationsIntegrationsRequestArgsProvidersItemGheServer, nil
	case "vercel":
		return InstallationsIntegrationsRequestArgsProvidersItemVercel, nil
	case "cloudflare":
		return InstallationsIntegrationsRequestArgsProvidersItemCloudflare, nil
	case "slack":
		return InstallationsIntegrationsRequestArgsProvidersItemSlack, nil
	case "cli":
		return InstallationsIntegrationsRequestArgsProvidersItemCli, nil
	}
	var t InstallationsIntegrationsRequestArgsProvidersItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InstallationsIntegrationsRequestArgsProvidersItem) Ptr() *InstallationsIntegrationsRequestArgsProvidersItem {
	return &i
}

var (
	linkSurfaceToDestinationIntegrationsRequestArgsFieldIntegrationID = big.NewInt(1 << 0)
	linkSurfaceToDestinationIntegrationsRequestArgsFieldProjectID     = big.NewInt(1 << 1)
	linkSurfaceToDestinationIntegrationsRequestArgsFieldSurfaceSlug   = big.NewInt(1 << 2)
)

type LinkSurfaceToDestinationIntegrationsRequestArgs struct {
	// Identifier of the existing integration installation.
	IntegrationID string `json:"integrationId" url:"integrationId"`
	// Destination project identifier exposed by the integration.
	ProjectID string `json:"projectId" url:"projectId"`
	// Surface URL slug, using lowercase letters, numbers, and hyphens.
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) GetIntegrationID() string {
	if l == nil {
		return ""
	}
	return l.IntegrationID
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) GetProjectID() string {
	if l == nil {
		return ""
	}
	return l.ProjectID
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) GetSurfaceSlug() string {
	if l == nil {
		return ""
	}
	return l.SurfaceSlug
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetIntegrationID sets the IntegrationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) SetIntegrationID(integrationID string) {
	l.IntegrationID = integrationID
	l.require(linkSurfaceToDestinationIntegrationsRequestArgsFieldIntegrationID)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) SetProjectID(projectID string) {
	l.ProjectID = projectID
	l.require(linkSurfaceToDestinationIntegrationsRequestArgsFieldProjectID)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	l.SurfaceSlug = surfaceSlug
	l.require(linkSurfaceToDestinationIntegrationsRequestArgsFieldSurfaceSlug)
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkSurfaceToDestinationIntegrationsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LinkSurfaceToDestinationIntegrationsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed LinkSurfaceToDestinationIntegrationsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LinkSurfaceToDestinationIntegrationsRequestArgs) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	linkSurfaceToRepositoryIntegrationsRequestArgsFieldIntegrationID    = big.NewInt(1 << 0)
	linkSurfaceToRepositoryIntegrationsRequestArgsFieldRepositoryID     = big.NewInt(1 << 1)
	linkSurfaceToRepositoryIntegrationsRequestArgsFieldSurfaceSlug      = big.NewInt(1 << 2)
	linkSurfaceToRepositoryIntegrationsRequestArgsFieldWorkingDirectory = big.NewInt(1 << 3)
)

// linkSurfaceToRepositoryIntegrationsRequestArgsNullableFields maps the wire names of LinkSurfaceToRepositoryIntegrationsRequestArgs's nullable fields (required or optional) to their field bits.
var linkSurfaceToRepositoryIntegrationsRequestArgsNullableFields = map[string]*big.Int{
	"workingDirectory": linkSurfaceToRepositoryIntegrationsRequestArgsFieldWorkingDirectory,
}

type LinkSurfaceToRepositoryIntegrationsRequestArgs struct {
	// Identifier of the existing integration installation.
	IntegrationID string `json:"integrationId" url:"integrationId"`
	// Repository identifier exposed by the integration.
	RepositoryID string `json:"repositoryId" url:"repositoryId"`
	// Surface URL slug, using lowercase letters, numbers, and hyphens.
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`
	// Repository-relative working directory. Omit for the repository root.
	WorkingDirectory *string `json:"workingDirectory,omitempty" url:"workingDirectory,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) GetIntegrationID() string {
	if l == nil {
		return ""
	}
	return l.IntegrationID
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) GetRepositoryID() string {
	if l == nil {
		return ""
	}
	return l.RepositoryID
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) GetSurfaceSlug() string {
	if l == nil {
		return ""
	}
	return l.SurfaceSlug
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) GetWorkingDirectory() *string {
	if l == nil {
		return nil
	}
	return l.WorkingDirectory
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetIntegrationID sets the IntegrationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) SetIntegrationID(integrationID string) {
	l.IntegrationID = integrationID
	l.require(linkSurfaceToRepositoryIntegrationsRequestArgsFieldIntegrationID)
}

// SetRepositoryID sets the RepositoryID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) SetRepositoryID(repositoryID string) {
	l.RepositoryID = repositoryID
	l.require(linkSurfaceToRepositoryIntegrationsRequestArgsFieldRepositoryID)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	l.SurfaceSlug = surfaceSlug
	l.require(linkSurfaceToRepositoryIntegrationsRequestArgsFieldSurfaceSlug)
}

// SetWorkingDirectory sets the WorkingDirectory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) SetWorkingDirectory(workingDirectory *string) {
	l.WorkingDirectory = workingDirectory
	l.require(linkSurfaceToRepositoryIntegrationsRequestArgsFieldWorkingDirectory)
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkSurfaceToRepositoryIntegrationsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LinkSurfaceToRepositoryIntegrationsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, linkSurfaceToRepositoryIntegrationsRequestArgsNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		l.require(presentFields)
	}
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed LinkSurfaceToRepositoryIntegrationsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LinkSurfaceToRepositoryIntegrationsRequestArgs) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	unlinkSurfaceDestinationMappingIntegrationsRequestArgsFieldSurfaceSlug = big.NewInt(1 << 0)
)

type UnlinkSurfaceDestinationMappingIntegrationsRequestArgs struct {
	// Surface URL slug, using lowercase letters, numbers, and hyphens.
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) GetSurfaceSlug() string {
	if u == nil {
		return ""
	}
	return u.SurfaceSlug
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	u.SurfaceSlug = surfaceSlug
	u.require(unlinkSurfaceDestinationMappingIntegrationsRequestArgsFieldSurfaceSlug)
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler UnlinkSurfaceDestinationMappingIntegrationsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnlinkSurfaceDestinationMappingIntegrationsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed UnlinkSurfaceDestinationMappingIntegrationsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unlinkSurfaceMappingIntegrationsRequestArgsFieldSurfaceSlug = big.NewInt(1 << 0)
)

type UnlinkSurfaceMappingIntegrationsRequestArgs struct {
	// Surface URL slug, using lowercase letters, numbers, and hyphens.
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) GetSurfaceSlug() string {
	if u == nil {
		return ""
	}
	return u.SurfaceSlug
}

func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	u.SurfaceSlug = surfaceSlug
	u.require(unlinkSurfaceMappingIntegrationsRequestArgsFieldSurfaceSlug)
}

func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler UnlinkSurfaceMappingIntegrationsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnlinkSurfaceMappingIntegrationsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed UnlinkSurfaceMappingIntegrationsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnlinkSurfaceMappingIntegrationsRequestArgs) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	unlinkSurfaceDestinationMappingIntegrationsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	unlinkSurfaceDestinationMappingIntegrationsRequestFieldArgs          = big.NewInt(1 << 1)
)

type UnlinkSurfaceDestinationMappingIntegrationsRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string                                                  `json:"-" url:"-"`
	Args          *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequest) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkSurfaceDestinationMappingIntegrationsRequest) SetWorkspaceSlug(workspaceSlug string) {
	u.WorkspaceSlug = workspaceSlug
	u.require(unlinkSurfaceDestinationMappingIntegrationsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkSurfaceDestinationMappingIntegrationsRequest) SetArgs(args *UnlinkSurfaceDestinationMappingIntegrationsRequestArgs) {
	u.Args = args
	u.require(unlinkSurfaceDestinationMappingIntegrationsRequestFieldArgs)
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UnlinkSurfaceDestinationMappingIntegrationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UnlinkSurfaceDestinationMappingIntegrationsRequest(body)
	return nil
}

func (u *UnlinkSurfaceDestinationMappingIntegrationsRequest) MarshalJSON() ([]byte, error) {
	type embed UnlinkSurfaceDestinationMappingIntegrationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	unlinkSurfaceMappingIntegrationsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	unlinkSurfaceMappingIntegrationsRequestFieldArgs          = big.NewInt(1 << 1)
)

type UnlinkSurfaceMappingIntegrationsRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string                                       `json:"-" url:"-"`
	Args          *UnlinkSurfaceMappingIntegrationsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UnlinkSurfaceMappingIntegrationsRequest) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkSurfaceMappingIntegrationsRequest) SetWorkspaceSlug(workspaceSlug string) {
	u.WorkspaceSlug = workspaceSlug
	u.require(unlinkSurfaceMappingIntegrationsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnlinkSurfaceMappingIntegrationsRequest) SetArgs(args *UnlinkSurfaceMappingIntegrationsRequestArgs) {
	u.Args = args
	u.require(unlinkSurfaceMappingIntegrationsRequestFieldArgs)
}

func (u *UnlinkSurfaceMappingIntegrationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UnlinkSurfaceMappingIntegrationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UnlinkSurfaceMappingIntegrationsRequest(body)
	return nil
}

func (u *UnlinkSurfaceMappingIntegrationsRequest) MarshalJSON() ([]byte, error) {
	type embed UnlinkSurfaceMappingIntegrationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
