// Code generated by Fern. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	createSurfaceRequestFieldWorkspaceSlug  = big.NewInt(1 << 0)
	createSurfaceRequestFieldAPIKey         = big.NewInt(1 << 1)
	createSurfaceRequestFieldIdempotencyKey = big.NewInt(1 << 2)
	createSurfaceRequestFieldName           = big.NewInt(1 << 3)
	createSurfaceRequestFieldType           = big.NewInt(1 << 4)
)

type CreateSurfaceRequest struct {
	WorkspaceSlug  string                      `json:"-" url:"-"`
	APIKey         *CreateSurfaceRequestAPIKey `json:"apiKey" url:"-"`
	IdempotencyKey string                      `json:"idempotencyKey" url:"-"`
	Name           string                      `json:"name" url:"-"`
	Type           CreateSurfaceRequestType    `json:"type" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSurfaceRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequest) SetWorkspaceSlug(workspaceSlug string) {
	c.WorkspaceSlug = workspaceSlug
	c.require(createSurfaceRequestFieldWorkspaceSlug)
}

// SetAPIKey sets the APIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequest) SetAPIKey(apiKey *CreateSurfaceRequestAPIKey) {
	c.APIKey = apiKey
	c.require(createSurfaceRequestFieldAPIKey)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createSurfaceRequestFieldIdempotencyKey)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequest) SetName(name string) {
	c.Name = name
	c.require(createSurfaceRequestFieldName)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequest) SetType(type_ CreateSurfaceRequestType) {
	c.Type = type_
	c.require(createSurfaceRequestFieldType)
}

func (c *CreateSurfaceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSurfaceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSurfaceRequest(body)
	return nil
}

func (c *CreateSurfaceRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSurfaceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createSurfaceResponseFieldAPIKey    = big.NewInt(1 << 0)
	createSurfaceResponseFieldPublicKey = big.NewInt(1 << 1)
	createSurfaceResponseFieldSurface   = big.NewInt(1 << 2)
)

type CreateSurfaceResponse struct {
	APIKey    *CreateSurfaceResponseAPIKey  `json:"apiKey" url:"apiKey"`
	PublicKey string                        `json:"publicKey" url:"publicKey"`
	Surface   *CreateSurfaceResponseSurface `json:"surface" url:"surface"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSurfaceResponse) GetAPIKey() *CreateSurfaceResponseAPIKey {
	if c == nil {
		return nil
	}
	return c.APIKey
}

func (c *CreateSurfaceResponse) GetPublicKey() string {
	if c == nil {
		return ""
	}
	return c.PublicKey
}

func (c *CreateSurfaceResponse) GetSurface() *CreateSurfaceResponseSurface {
	if c == nil {
		return nil
	}
	return c.Surface
}

func (c *CreateSurfaceResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSurfaceResponse) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetAPIKey sets the APIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponse) SetAPIKey(apiKey *CreateSurfaceResponseAPIKey) {
	c.APIKey = apiKey
	c.require(createSurfaceResponseFieldAPIKey)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponse) SetPublicKey(publicKey string) {
	c.PublicKey = publicKey
	c.require(createSurfaceResponseFieldPublicKey)
}

// SetSurface sets the Surface field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponse) SetSurface(surface *CreateSurfaceResponseSurface) {
	c.Surface = surface
	c.require(createSurfaceResponseFieldSurface)
}

func (c *CreateSurfaceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSurfaceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSurfaceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSurfaceResponse) MarshalJSON() ([]byte, error) {
	type embed CreateSurfaceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSurfaceResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSurfaceResponseAPIKeyFieldID     = big.NewInt(1 << 0)
	createSurfaceResponseAPIKeyFieldName   = big.NewInt(1 << 1)
	createSurfaceResponseAPIKeyFieldSecret = big.NewInt(1 << 2)
)

type CreateSurfaceResponseAPIKey struct {
	ID     string                          `json:"id" url:"id"`
	Name   CreateSurfaceResponseAPIKeyName `json:"name" url:"name"`
	Secret string                          `json:"secret" url:"secret"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSurfaceResponseAPIKey) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateSurfaceResponseAPIKey) GetName() CreateSurfaceResponseAPIKeyName {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSurfaceResponseAPIKey) GetSecret() string {
	if c == nil {
		return ""
	}
	return c.Secret
}

func (c *CreateSurfaceResponseAPIKey) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSurfaceResponseAPIKey) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseAPIKey) SetID(id string) {
	c.ID = id
	c.require(createSurfaceResponseAPIKeyFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseAPIKey) SetName(name CreateSurfaceResponseAPIKeyName) {
	c.Name = name
	c.require(createSurfaceResponseAPIKeyFieldName)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseAPIKey) SetSecret(secret string) {
	c.Secret = secret
	c.require(createSurfaceResponseAPIKeyFieldSecret)
}

func (c *CreateSurfaceResponseAPIKey) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSurfaceResponseAPIKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSurfaceResponseAPIKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSurfaceResponseAPIKey) MarshalJSON() ([]byte, error) {
	type embed CreateSurfaceResponseAPIKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSurfaceResponseAPIKey) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateSurfaceResponseAPIKeyName string

const (
	CreateSurfaceResponseAPIKeyNameDefault CreateSurfaceResponseAPIKeyName = "Default"
)

func NewCreateSurfaceResponseAPIKeyNameFromString(s string) (CreateSurfaceResponseAPIKeyName, error) {
	switch s {
	case "Default":
		return CreateSurfaceResponseAPIKeyNameDefault, nil
	}
	var t CreateSurfaceResponseAPIKeyName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSurfaceResponseAPIKeyName) Ptr() *CreateSurfaceResponseAPIKeyName {
	return &c
}

var (
	createSurfaceResponseSurfaceFieldID   = big.NewInt(1 << 0)
	createSurfaceResponseSurfaceFieldName = big.NewInt(1 << 1)
	createSurfaceResponseSurfaceFieldSlug = big.NewInt(1 << 2)
	createSurfaceResponseSurfaceFieldType = big.NewInt(1 << 3)
)

type CreateSurfaceResponseSurface struct {
	ID   string                           `json:"id" url:"id"`
	Name string                           `json:"name" url:"name"`
	Slug string                           `json:"slug" url:"slug"`
	Type CreateSurfaceResponseSurfaceType `json:"type" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSurfaceResponseSurface) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateSurfaceResponseSurface) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSurfaceResponseSurface) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *CreateSurfaceResponseSurface) GetType() CreateSurfaceResponseSurfaceType {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreateSurfaceResponseSurface) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSurfaceResponseSurface) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseSurface) SetID(id string) {
	c.ID = id
	c.require(createSurfaceResponseSurfaceFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseSurface) SetName(name string) {
	c.Name = name
	c.require(createSurfaceResponseSurfaceFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseSurface) SetSlug(slug string) {
	c.Slug = slug
	c.require(createSurfaceResponseSurfaceFieldSlug)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceResponseSurface) SetType(type_ CreateSurfaceResponseSurfaceType) {
	c.Type = type_
	c.require(createSurfaceResponseSurfaceFieldType)
}

func (c *CreateSurfaceResponseSurface) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSurfaceResponseSurface
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSurfaceResponseSurface(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSurfaceResponseSurface) MarshalJSON() ([]byte, error) {
	type embed CreateSurfaceResponseSurface
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSurfaceResponseSurface) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateSurfaceResponseSurfaceType string

const (
	CreateSurfaceResponseSurfaceTypeElysia CreateSurfaceResponseSurfaceType = "elysia"
	CreateSurfaceResponseSurfaceTypeNest   CreateSurfaceResponseSurfaceType = "nest"
	CreateSurfaceResponseSurfaceTypeNextjs CreateSurfaceResponseSurfaceType = "nextjs"
	CreateSurfaceResponseSurfaceTypePython CreateSurfaceResponseSurfaceType = "python"
	CreateSurfaceResponseSurfaceTypeReact  CreateSurfaceResponseSurfaceType = "react"
)

func NewCreateSurfaceResponseSurfaceTypeFromString(s string) (CreateSurfaceResponseSurfaceType, error) {
	switch s {
	case "elysia":
		return CreateSurfaceResponseSurfaceTypeElysia, nil
	case "nest":
		return CreateSurfaceResponseSurfaceTypeNest, nil
	case "nextjs":
		return CreateSurfaceResponseSurfaceTypeNextjs, nil
	case "python":
		return CreateSurfaceResponseSurfaceTypePython, nil
	case "react":
		return CreateSurfaceResponseSurfaceTypeReact, nil
	}
	var t CreateSurfaceResponseSurfaceType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSurfaceResponseSurfaceType) Ptr() *CreateSurfaceResponseSurfaceType {
	return &c
}

var (
	createSurfaceRequestAPIKeyFieldScopes                 = big.NewInt(1 << 0)
	createSurfaceRequestAPIKeyFieldSecondsUntilExpiration = big.NewInt(1 << 1)
)

// createSurfaceRequestAPIKeyNullableFields maps the wire names of CreateSurfaceRequestAPIKey's nullable fields (required or optional) to their field bits.
var createSurfaceRequestAPIKeyNullableFields = map[string]*big.Int{
	"secondsUntilExpiration": createSurfaceRequestAPIKeyFieldSecondsUntilExpiration,
}

type CreateSurfaceRequestAPIKey struct {
	Scopes                 []CreateSurfaceRequestAPIKeyScopesItem `json:"scopes" url:"scopes"`
	SecondsUntilExpiration *int                                   `json:"secondsUntilExpiration,omitempty" url:"secondsUntilExpiration,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSurfaceRequestAPIKey) GetScopes() []CreateSurfaceRequestAPIKeyScopesItem {
	if c == nil {
		return nil
	}
	return c.Scopes
}

func (c *CreateSurfaceRequestAPIKey) GetSecondsUntilExpiration() *int {
	if c == nil {
		return nil
	}
	return c.SecondsUntilExpiration
}

func (c *CreateSurfaceRequestAPIKey) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSurfaceRequestAPIKey) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequestAPIKey) SetScopes(scopes []CreateSurfaceRequestAPIKeyScopesItem) {
	c.Scopes = scopes
	c.require(createSurfaceRequestAPIKeyFieldScopes)
}

// SetSecondsUntilExpiration sets the SecondsUntilExpiration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSurfaceRequestAPIKey) SetSecondsUntilExpiration(secondsUntilExpiration *int) {
	c.SecondsUntilExpiration = secondsUntilExpiration
	c.require(createSurfaceRequestAPIKeyFieldSecondsUntilExpiration)
}

func (c *CreateSurfaceRequestAPIKey) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSurfaceRequestAPIKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSurfaceRequestAPIKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, createSurfaceRequestAPIKeyNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		c.require(presentFields)
	}
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSurfaceRequestAPIKey) MarshalJSON() ([]byte, error) {
	type embed CreateSurfaceRequestAPIKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSurfaceRequestAPIKey) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateSurfaceRequestAPIKeyScopesItem string

const (
	CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesRead               CreateSurfaceRequestAPIKeyScopesItem = "org:surfaces:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesWrite              CreateSurfaceRequestAPIKeyScopesItem = "org:surfaces:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesDelete             CreateSurfaceRequestAPIKeyScopesItem = "org:surfaces:delete"
	CreateSurfaceRequestAPIKeyScopesItemOrgProblemsRead               CreateSurfaceRequestAPIKeyScopesItem = "org:problems:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgProblemsWrite              CreateSurfaceRequestAPIKeyScopesItem = "org:problems:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgSupportRead                CreateSurfaceRequestAPIKeyScopesItem = "org:support:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgSupportWrite               CreateSurfaceRequestAPIKeyScopesItem = "org:support:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgReplaysRead                CreateSurfaceRequestAPIKeyScopesItem = "org:replays:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgSourceContextRead          CreateSurfaceRequestAPIKeyScopesItem = "org:source_context:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgIntegrationSettingsRead    CreateSurfaceRequestAPIKeyScopesItem = "org:integration_settings:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgIntegrationSettingsWrite   CreateSurfaceRequestAPIKeyScopesItem = "org:integration_settings:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceMembersRead       CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_members:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceMembersWrite      CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_members:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBillingRead       CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_billing:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBillingWrite      CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_billing:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBasicsRead        CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_basics:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBasicsWrite       CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_basics:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceDomainsRead       CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_domains:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceDomainsWrite      CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_domains:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceAuthRead          CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_auth:read"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceAuthWrite         CreateSurfaceRequestAPIKeyScopesItem = "org:workspace_auth:write"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceDestroy           CreateSurfaceRequestAPIKeyScopesItem = "org:workspace:destroy"
	CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceTransferOwnership CreateSurfaceRequestAPIKeyScopesItem = "org:workspace:transfer_ownership"
	CreateSurfaceRequestAPIKeyScopesItemReleaseWrite                  CreateSurfaceRequestAPIKeyScopesItem = "release:write"
	CreateSurfaceRequestAPIKeyScopesItemIngestWrite                   CreateSurfaceRequestAPIKeyScopesItem = "ingest:write"
)

func NewCreateSurfaceRequestAPIKeyScopesItemFromString(s string) (CreateSurfaceRequestAPIKeyScopesItem, error) {
	switch s {
	case "org:surfaces:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesRead, nil
	case "org:surfaces:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesWrite, nil
	case "org:surfaces:delete":
		return CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesDelete, nil
	case "org:problems:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgProblemsRead, nil
	case "org:problems:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgProblemsWrite, nil
	case "org:support:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgSupportRead, nil
	case "org:support:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgSupportWrite, nil
	case "org:replays:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgReplaysRead, nil
	case "org:source_context:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgSourceContextRead, nil
	case "org:integration_settings:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgIntegrationSettingsRead, nil
	case "org:integration_settings:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgIntegrationSettingsWrite, nil
	case "org:workspace_members:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceMembersRead, nil
	case "org:workspace_members:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceMembersWrite, nil
	case "org:workspace_billing:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBillingRead, nil
	case "org:workspace_billing:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBillingWrite, nil
	case "org:workspace_basics:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBasicsRead, nil
	case "org:workspace_basics:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceBasicsWrite, nil
	case "org:workspace_domains:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceDomainsRead, nil
	case "org:workspace_domains:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceDomainsWrite, nil
	case "org:workspace_auth:read":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceAuthRead, nil
	case "org:workspace_auth:write":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceAuthWrite, nil
	case "org:workspace:destroy":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceDestroy, nil
	case "org:workspace:transfer_ownership":
		return CreateSurfaceRequestAPIKeyScopesItemOrgWorkspaceTransferOwnership, nil
	case "release:write":
		return CreateSurfaceRequestAPIKeyScopesItemReleaseWrite, nil
	case "ingest:write":
		return CreateSurfaceRequestAPIKeyScopesItemIngestWrite, nil
	}
	var t CreateSurfaceRequestAPIKeyScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSurfaceRequestAPIKeyScopesItem) Ptr() *CreateSurfaceRequestAPIKeyScopesItem {
	return &c
}

type CreateSurfaceRequestType string

const (
	CreateSurfaceRequestTypeElysia CreateSurfaceRequestType = "elysia"
	CreateSurfaceRequestTypeNest   CreateSurfaceRequestType = "nest"
	CreateSurfaceRequestTypeNextjs CreateSurfaceRequestType = "nextjs"
	CreateSurfaceRequestTypePython CreateSurfaceRequestType = "python"
	CreateSurfaceRequestTypeReact  CreateSurfaceRequestType = "react"
)

func NewCreateSurfaceRequestTypeFromString(s string) (CreateSurfaceRequestType, error) {
	switch s {
	case "elysia":
		return CreateSurfaceRequestTypeElysia, nil
	case "nest":
		return CreateSurfaceRequestTypeNest, nil
	case "nextjs":
		return CreateSurfaceRequestTypeNextjs, nil
	case "python":
		return CreateSurfaceRequestTypePython, nil
	case "react":
		return CreateSurfaceRequestTypeReact, nil
	}
	var t CreateSurfaceRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSurfaceRequestType) Ptr() *CreateSurfaceRequestType {
	return &c
}
