// Code generated by Fern. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	createWorkspaceAPIKeyRequestFieldWorkspaceSlug          = big.NewInt(1 << 0)
	createWorkspaceAPIKeyRequestFieldSurfaceSlug            = big.NewInt(1 << 1)
	createWorkspaceAPIKeyRequestFieldIdempotencyKey         = big.NewInt(1 << 2)
	createWorkspaceAPIKeyRequestFieldName                   = big.NewInt(1 << 3)
	createWorkspaceAPIKeyRequestFieldScopes                 = big.NewInt(1 << 4)
	createWorkspaceAPIKeyRequestFieldSecondsUntilExpiration = big.NewInt(1 << 5)
)

type CreateWorkspaceAPIKeyRequest struct {
	WorkspaceSlug          string                                   `json:"-" url:"-"`
	SurfaceSlug            *string                                  `json:"surfaceSlug,omitempty" url:"-"`
	IdempotencyKey         string                                   `json:"idempotencyKey" url:"-"`
	Name                   string                                   `json:"name" url:"-"`
	Scopes                 []CreateWorkspaceAPIKeyRequestScopesItem `json:"scopes" url:"-"`
	SecondsUntilExpiration *int                                     `json:"secondsUntilExpiration,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateWorkspaceAPIKeyRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyRequest) SetWorkspaceSlug(workspaceSlug string) {
	c.WorkspaceSlug = workspaceSlug
	c.require(createWorkspaceAPIKeyRequestFieldWorkspaceSlug)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyRequest) SetSurfaceSlug(surfaceSlug *string) {
	c.SurfaceSlug = surfaceSlug
	c.require(createWorkspaceAPIKeyRequestFieldSurfaceSlug)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createWorkspaceAPIKeyRequestFieldIdempotencyKey)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyRequest) SetName(name string) {
	c.Name = name
	c.require(createWorkspaceAPIKeyRequestFieldName)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyRequest) SetScopes(scopes []CreateWorkspaceAPIKeyRequestScopesItem) {
	c.Scopes = scopes
	c.require(createWorkspaceAPIKeyRequestFieldScopes)
}

// SetSecondsUntilExpiration sets the SecondsUntilExpiration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyRequest) SetSecondsUntilExpiration(secondsUntilExpiration *int) {
	c.SecondsUntilExpiration = secondsUntilExpiration
	c.require(createWorkspaceAPIKeyRequestFieldSecondsUntilExpiration)
}

func (c *CreateWorkspaceAPIKeyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWorkspaceAPIKeyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateWorkspaceAPIKeyRequest(body)
	return nil
}

func (c *CreateWorkspaceAPIKeyRequest) MarshalJSON() ([]byte, error) {
	type embed CreateWorkspaceAPIKeyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mutationOrganizationsUpdateBasicsRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	mutationOrganizationsUpdateBasicsRequestFieldArgs          = big.NewInt(1 << 1)
)

type MutationOrganizationsUpdateBasicsRequest struct {
	WorkspaceSlug string                                        `json:"-" url:"-"`
	Args          *MutationOrganizationsUpdateBasicsRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MutationOrganizationsUpdateBasicsRequest) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsUpdateBasicsRequest) SetWorkspaceSlug(workspaceSlug string) {
	m.WorkspaceSlug = workspaceSlug
	m.require(mutationOrganizationsUpdateBasicsRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsUpdateBasicsRequest) SetArgs(args *MutationOrganizationsUpdateBasicsRequestArgs) {
	m.Args = args
	m.require(mutationOrganizationsUpdateBasicsRequestFieldArgs)
}

func (m *MutationOrganizationsUpdateBasicsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationOrganizationsUpdateBasicsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MutationOrganizationsUpdateBasicsRequest(body)
	return nil
}

func (m *MutationOrganizationsUpdateBasicsRequest) MarshalJSON() ([]byte, error) {
	type embed MutationOrganizationsUpdateBasicsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mutationSurfacesDeleteRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	mutationSurfacesDeleteRequestFieldArgs          = big.NewInt(1 << 1)
)

type MutationSurfacesDeleteRequest struct {
	WorkspaceSlug string                             `json:"-" url:"-"`
	Args          *MutationSurfacesDeleteRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MutationSurfacesDeleteRequest) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesDeleteRequest) SetWorkspaceSlug(workspaceSlug string) {
	m.WorkspaceSlug = workspaceSlug
	m.require(mutationSurfacesDeleteRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesDeleteRequest) SetArgs(args *MutationSurfacesDeleteRequestArgs) {
	m.Args = args
	m.require(mutationSurfacesDeleteRequestFieldArgs)
}

func (m *MutationSurfacesDeleteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationSurfacesDeleteRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MutationSurfacesDeleteRequest(body)
	return nil
}

func (m *MutationSurfacesDeleteRequest) MarshalJSON() ([]byte, error) {
	type embed MutationSurfacesDeleteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mutationSurfacesUpdateNameRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	mutationSurfacesUpdateNameRequestFieldArgs          = big.NewInt(1 << 1)
)

type MutationSurfacesUpdateNameRequest struct {
	WorkspaceSlug string                                 `json:"-" url:"-"`
	Args          *MutationSurfacesUpdateNameRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MutationSurfacesUpdateNameRequest) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesUpdateNameRequest) SetWorkspaceSlug(workspaceSlug string) {
	m.WorkspaceSlug = workspaceSlug
	m.require(mutationSurfacesUpdateNameRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesUpdateNameRequest) SetArgs(args *MutationSurfacesUpdateNameRequestArgs) {
	m.Args = args
	m.require(mutationSurfacesUpdateNameRequestFieldArgs)
}

func (m *MutationSurfacesUpdateNameRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationSurfacesUpdateNameRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MutationSurfacesUpdateNameRequest(body)
	return nil
}

func (m *MutationSurfacesUpdateNameRequest) MarshalJSON() ([]byte, error) {
	type embed MutationSurfacesUpdateNameRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	queryOrganizationsCurrentRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	queryOrganizationsCurrentRequestFieldArgs          = big.NewInt(1 << 1)
)

type QueryOrganizationsCurrentRequest struct {
	WorkspaceSlug string         `json:"-" url:"-"`
	Args          map[string]any `json:"args,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QueryOrganizationsCurrentRequest) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentRequest) SetWorkspaceSlug(workspaceSlug string) {
	q.WorkspaceSlug = workspaceSlug
	q.require(queryOrganizationsCurrentRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentRequest) SetArgs(args map[string]any) {
	q.Args = args
	q.require(queryOrganizationsCurrentRequestFieldArgs)
}

func (q *QueryOrganizationsCurrentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler QueryOrganizationsCurrentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*q = QueryOrganizationsCurrentRequest(body)
	return nil
}

func (q *QueryOrganizationsCurrentRequest) MarshalJSON() ([]byte, error) {
	type embed QueryOrganizationsCurrentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	querySurfacesGetBySlugIncludeDeletedRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	querySurfacesGetBySlugIncludeDeletedRequestFieldArgs          = big.NewInt(1 << 1)
)

type QuerySurfacesGetBySlugIncludeDeletedRequest struct {
	WorkspaceSlug string                                           `json:"-" url:"-"`
	Args          *QuerySurfacesGetBySlugIncludeDeletedRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequest) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedRequest) SetWorkspaceSlug(workspaceSlug string) {
	q.WorkspaceSlug = workspaceSlug
	q.require(querySurfacesGetBySlugIncludeDeletedRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedRequest) SetArgs(args *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) {
	q.Args = args
	q.require(querySurfacesGetBySlugIncludeDeletedRequestFieldArgs)
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler QuerySurfacesGetBySlugIncludeDeletedRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*q = QuerySurfacesGetBySlugIncludeDeletedRequest(body)
	return nil
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequest) MarshalJSON() ([]byte, error) {
	type embed QuerySurfacesGetBySlugIncludeDeletedRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	readPrivateKeyRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	readPrivateKeyRequestFieldAPIKeyID      = big.NewInt(1 << 1)
)

type ReadPrivateKeyRequest struct {
	WorkspaceSlug string `json:"-" url:"-"`
	APIKeyID      string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReadPrivateKeyRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyRequest) SetWorkspaceSlug(workspaceSlug string) {
	r.WorkspaceSlug = workspaceSlug
	r.require(readPrivateKeyRequestFieldWorkspaceSlug)
}

// SetAPIKeyID sets the APIKeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyRequest) SetAPIKeyID(apiKeyID string) {
	r.APIKeyID = apiKeyID
	r.require(readPrivateKeyRequestFieldAPIKeyID)
}

var (
	revokeWorkspaceAPIKeyRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	revokeWorkspaceAPIKeyRequestFieldAPIKeyID      = big.NewInt(1 << 1)
)

type RevokeWorkspaceAPIKeyRequest struct {
	WorkspaceSlug string `json:"-" url:"-"`
	APIKeyID      string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RevokeWorkspaceAPIKeyRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeWorkspaceAPIKeyRequest) SetWorkspaceSlug(workspaceSlug string) {
	r.WorkspaceSlug = workspaceSlug
	r.require(revokeWorkspaceAPIKeyRequestFieldWorkspaceSlug)
}

// SetAPIKeyID sets the APIKeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeWorkspaceAPIKeyRequest) SetAPIKeyID(apiKeyID string) {
	r.APIKeyID = apiKeyID
	r.require(revokeWorkspaceAPIKeyRequestFieldAPIKeyID)
}

var (
	createWorkspaceAPIKeyResponseFieldAPIKey = big.NewInt(1 << 0)
)

type CreateWorkspaceAPIKeyResponse struct {
	APIKey *CreateWorkspaceAPIKeyResponseAPIKey `json:"apiKey" url:"apiKey"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateWorkspaceAPIKeyResponse) GetAPIKey() *CreateWorkspaceAPIKeyResponseAPIKey {
	if c == nil {
		return nil
	}
	return c.APIKey
}

func (c *CreateWorkspaceAPIKeyResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateWorkspaceAPIKeyResponse) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetAPIKey sets the APIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyResponse) SetAPIKey(apiKey *CreateWorkspaceAPIKeyResponseAPIKey) {
	c.APIKey = apiKey
	c.require(createWorkspaceAPIKeyResponseFieldAPIKey)
}

func (c *CreateWorkspaceAPIKeyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWorkspaceAPIKeyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateWorkspaceAPIKeyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateWorkspaceAPIKeyResponse) MarshalJSON() ([]byte, error) {
	type embed CreateWorkspaceAPIKeyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateWorkspaceAPIKeyResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createWorkspaceAPIKeyResponseAPIKeyFieldID     = big.NewInt(1 << 0)
	createWorkspaceAPIKeyResponseAPIKeyFieldName   = big.NewInt(1 << 1)
	createWorkspaceAPIKeyResponseAPIKeyFieldSecret = big.NewInt(1 << 2)
)

type CreateWorkspaceAPIKeyResponseAPIKey struct {
	ID     string `json:"id" url:"id"`
	Name   string `json:"name" url:"name"`
	Secret string `json:"secret" url:"secret"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) GetSecret() string {
	if c == nil {
		return ""
	}
	return c.Secret
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyResponseAPIKey) SetID(id string) {
	c.ID = id
	c.require(createWorkspaceAPIKeyResponseAPIKeyFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyResponseAPIKey) SetName(name string) {
	c.Name = name
	c.require(createWorkspaceAPIKeyResponseAPIKeyFieldName)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWorkspaceAPIKeyResponseAPIKey) SetSecret(secret string) {
	c.Secret = secret
	c.require(createWorkspaceAPIKeyResponseAPIKeyFieldSecret)
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWorkspaceAPIKeyResponseAPIKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateWorkspaceAPIKeyResponseAPIKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) MarshalJSON() ([]byte, error) {
	type embed CreateWorkspaceAPIKeyResponseAPIKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateWorkspaceAPIKeyResponseAPIKey) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	mutationOrganizationsUpdateBasicsResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationOrganizationsUpdateBasicsResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationOrganizationsUpdateBasicsResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationOrganizationsUpdateBasicsResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationOrganizationsUpdateBasicsResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsUpdateBasicsResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationOrganizationsUpdateBasicsResponseFieldSuccess)
}

func (m *MutationOrganizationsUpdateBasicsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationOrganizationsUpdateBasicsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationOrganizationsUpdateBasicsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationOrganizationsUpdateBasicsResponse) MarshalJSON() ([]byte, error) {
	type embed MutationOrganizationsUpdateBasicsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationOrganizationsUpdateBasicsResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationSurfacesDeleteResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationSurfacesDeleteResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationSurfacesDeleteResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationSurfacesDeleteResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationSurfacesDeleteResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesDeleteResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationSurfacesDeleteResponseFieldSuccess)
}

func (m *MutationSurfacesDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationSurfacesDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationSurfacesDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationSurfacesDeleteResponse) MarshalJSON() ([]byte, error) {
	type embed MutationSurfacesDeleteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationSurfacesDeleteResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationSurfacesUpdateNameResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationSurfacesUpdateNameResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationSurfacesUpdateNameResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationSurfacesUpdateNameResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationSurfacesUpdateNameResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesUpdateNameResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationSurfacesUpdateNameResponseFieldSuccess)
}

func (m *MutationSurfacesUpdateNameResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationSurfacesUpdateNameResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationSurfacesUpdateNameResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationSurfacesUpdateNameResponse) MarshalJSON() ([]byte, error) {
	type embed MutationSurfacesUpdateNameResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationSurfacesUpdateNameResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	queryOrganizationsCurrentResponseFieldID                    = big.NewInt(1 << 0)
	queryOrganizationsCurrentResponseFieldName                  = big.NewInt(1 << 1)
	queryOrganizationsCurrentResponseFieldSlug                  = big.NewInt(1 << 2)
	queryOrganizationsCurrentResponseFieldDataResidencyLocation = big.NewInt(1 << 3)
)

type QueryOrganizationsCurrentResponse struct {
	ID                    string                                                 `json:"id" url:"id"`
	Name                  string                                                 `json:"name" url:"name"`
	Slug                  string                                                 `json:"slug" url:"slug"`
	DataResidencyLocation QueryOrganizationsCurrentResponseDataResidencyLocation `json:"dataResidencyLocation" url:"dataResidencyLocation"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (q *QueryOrganizationsCurrentResponse) GetID() string {
	if q == nil {
		return ""
	}
	return q.ID
}

func (q *QueryOrganizationsCurrentResponse) GetName() string {
	if q == nil {
		return ""
	}
	return q.Name
}

func (q *QueryOrganizationsCurrentResponse) GetSlug() string {
	if q == nil {
		return ""
	}
	return q.Slug
}

func (q *QueryOrganizationsCurrentResponse) GetDataResidencyLocation() QueryOrganizationsCurrentResponseDataResidencyLocation {
	if q == nil {
		return ""
	}
	return q.DataResidencyLocation
}

func (q *QueryOrganizationsCurrentResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.ExtraProperties
}

func (q *QueryOrganizationsCurrentResponse) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetID(id string) {
	q.ID = id
	q.require(queryOrganizationsCurrentResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetName(name string) {
	q.Name = name
	q.require(queryOrganizationsCurrentResponseFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetSlug(slug string) {
	q.Slug = slug
	q.require(queryOrganizationsCurrentResponseFieldSlug)
}

// SetDataResidencyLocation sets the DataResidencyLocation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetDataResidencyLocation(dataResidencyLocation QueryOrganizationsCurrentResponseDataResidencyLocation) {
	q.DataResidencyLocation = dataResidencyLocation
	q.require(queryOrganizationsCurrentResponseFieldDataResidencyLocation)
}

func (q *QueryOrganizationsCurrentResponse) UnmarshalJSON(data []byte) error {
	type embed QueryOrganizationsCurrentResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QueryOrganizationsCurrentResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.ExtraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueryOrganizationsCurrentResponse) MarshalJSON() ([]byte, error) {
	type embed QueryOrganizationsCurrentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, q.ExtraProperties)
}

func (q *QueryOrganizationsCurrentResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

type QueryOrganizationsCurrentResponseDataResidencyLocation string

const (
	QueryOrganizationsCurrentResponseDataResidencyLocationUs QueryOrganizationsCurrentResponseDataResidencyLocation = "us"
	QueryOrganizationsCurrentResponseDataResidencyLocationEu QueryOrganizationsCurrentResponseDataResidencyLocation = "eu"
)

func NewQueryOrganizationsCurrentResponseDataResidencyLocationFromString(s string) (QueryOrganizationsCurrentResponseDataResidencyLocation, error) {
	switch s {
	case "us":
		return QueryOrganizationsCurrentResponseDataResidencyLocationUs, nil
	case "eu":
		return QueryOrganizationsCurrentResponseDataResidencyLocationEu, nil
	}
	var t QueryOrganizationsCurrentResponseDataResidencyLocation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryOrganizationsCurrentResponseDataResidencyLocation) Ptr() *QueryOrganizationsCurrentResponseDataResidencyLocation {
	return &q
}

var (
	querySurfacesGetBySlugIncludeDeletedResponseFieldID        = big.NewInt(1 << 0)
	querySurfacesGetBySlugIncludeDeletedResponseFieldName      = big.NewInt(1 << 1)
	querySurfacesGetBySlugIncludeDeletedResponseFieldSlug      = big.NewInt(1 << 2)
	querySurfacesGetBySlugIncludeDeletedResponseFieldType      = big.NewInt(1 << 3)
	querySurfacesGetBySlugIncludeDeletedResponseFieldDeletedAt = big.NewInt(1 << 4)
)

// querySurfacesGetBySlugIncludeDeletedResponseNullableFields maps the wire names of QuerySurfacesGetBySlugIncludeDeletedResponse's nullable fields (required or optional) to their field bits.
var querySurfacesGetBySlugIncludeDeletedResponseNullableFields = map[string]*big.Int{
	"deletedAt": querySurfacesGetBySlugIncludeDeletedResponseFieldDeletedAt,
}

type QuerySurfacesGetBySlugIncludeDeletedResponse struct {
	ID        string                                           `json:"id" url:"id"`
	Name      string                                           `json:"name" url:"name"`
	Slug      string                                           `json:"slug" url:"slug"`
	Type      QuerySurfacesGetBySlugIncludeDeletedResponseType `json:"type" url:"type"`
	DeletedAt *float64                                         `json:"deletedAt,omitempty" url:"deletedAt,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) GetID() string {
	if q == nil {
		return ""
	}
	return q.ID
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) GetName() string {
	if q == nil {
		return ""
	}
	return q.Name
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) GetSlug() string {
	if q == nil {
		return ""
	}
	return q.Slug
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) GetType() QuerySurfacesGetBySlugIncludeDeletedResponseType {
	if q == nil {
		return ""
	}
	return q.Type
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) GetDeletedAt() *float64 {
	if q == nil {
		return nil
	}
	return q.DeletedAt
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.ExtraProperties
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) SetID(id string) {
	q.ID = id
	q.require(querySurfacesGetBySlugIncludeDeletedResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) SetName(name string) {
	q.Name = name
	q.require(querySurfacesGetBySlugIncludeDeletedResponseFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) SetSlug(slug string) {
	q.Slug = slug
	q.require(querySurfacesGetBySlugIncludeDeletedResponseFieldSlug)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) SetType(type_ QuerySurfacesGetBySlugIncludeDeletedResponseType) {
	q.Type = type_
	q.require(querySurfacesGetBySlugIncludeDeletedResponseFieldType)
}

// SetDeletedAt sets the DeletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) SetDeletedAt(deletedAt *float64) {
	q.DeletedAt = deletedAt
	q.require(querySurfacesGetBySlugIncludeDeletedResponseFieldDeletedAt)
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) UnmarshalJSON(data []byte) error {
	type embed QuerySurfacesGetBySlugIncludeDeletedResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QuerySurfacesGetBySlugIncludeDeletedResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.ExtraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, querySurfacesGetBySlugIncludeDeletedResponseNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		q.require(presentFields)
	}
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) MarshalJSON() ([]byte, error) {
	type embed QuerySurfacesGetBySlugIncludeDeletedResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, q.ExtraProperties)
}

func (q *QuerySurfacesGetBySlugIncludeDeletedResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

type QuerySurfacesGetBySlugIncludeDeletedResponseType string

const (
	QuerySurfacesGetBySlugIncludeDeletedResponseTypeElysia QuerySurfacesGetBySlugIncludeDeletedResponseType = "elysia"
	QuerySurfacesGetBySlugIncludeDeletedResponseTypeNest   QuerySurfacesGetBySlugIncludeDeletedResponseType = "nest"
	QuerySurfacesGetBySlugIncludeDeletedResponseTypeNextjs QuerySurfacesGetBySlugIncludeDeletedResponseType = "nextjs"
	QuerySurfacesGetBySlugIncludeDeletedResponseTypePython QuerySurfacesGetBySlugIncludeDeletedResponseType = "python"
	QuerySurfacesGetBySlugIncludeDeletedResponseTypeReact  QuerySurfacesGetBySlugIncludeDeletedResponseType = "react"
)

func NewQuerySurfacesGetBySlugIncludeDeletedResponseTypeFromString(s string) (QuerySurfacesGetBySlugIncludeDeletedResponseType, error) {
	switch s {
	case "elysia":
		return QuerySurfacesGetBySlugIncludeDeletedResponseTypeElysia, nil
	case "nest":
		return QuerySurfacesGetBySlugIncludeDeletedResponseTypeNest, nil
	case "nextjs":
		return QuerySurfacesGetBySlugIncludeDeletedResponseTypeNextjs, nil
	case "python":
		return QuerySurfacesGetBySlugIncludeDeletedResponseTypePython, nil
	case "react":
		return QuerySurfacesGetBySlugIncludeDeletedResponseTypeReact, nil
	}
	var t QuerySurfacesGetBySlugIncludeDeletedResponseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QuerySurfacesGetBySlugIncludeDeletedResponseType) Ptr() *QuerySurfacesGetBySlugIncludeDeletedResponseType {
	return &q
}

var (
	readPrivateKeyResponseFieldID                     = big.NewInt(1 << 0)
	readPrivateKeyResponseFieldVersion                = big.NewInt(1 << 1)
	readPrivateKeyResponseFieldName                   = big.NewInt(1 << 2)
	readPrivateKeyResponseFieldSurfaceSlug            = big.NewInt(1 << 3)
	readPrivateKeyResponseFieldScopes                 = big.NewInt(1 << 4)
	readPrivateKeyResponseFieldSecondsUntilExpiration = big.NewInt(1 << 5)
	readPrivateKeyResponseFieldExpiresAt              = big.NewInt(1 << 6)
	readPrivateKeyResponseFieldRevoked                = big.NewInt(1 << 7)
)

// readPrivateKeyResponseNullableFields maps the wire names of ReadPrivateKeyResponse's nullable fields (required or optional) to their field bits.
var readPrivateKeyResponseNullableFields = map[string]*big.Int{
	"surfaceSlug":            readPrivateKeyResponseFieldSurfaceSlug,
	"secondsUntilExpiration": readPrivateKeyResponseFieldSecondsUntilExpiration,
	"expiresAt":              readPrivateKeyResponseFieldExpiresAt,
}

type ReadPrivateKeyResponse struct {
	ID                     string                             `json:"id" url:"id"`
	Version                string                             `json:"version" url:"version"`
	Name                   string                             `json:"name" url:"name"`
	SurfaceSlug            *string                            `json:"surfaceSlug,omitempty" url:"surfaceSlug,omitempty"`
	Scopes                 []ReadPrivateKeyResponseScopesItem `json:"scopes" url:"scopes"`
	SecondsUntilExpiration *int                               `json:"secondsUntilExpiration,omitempty" url:"secondsUntilExpiration,omitempty"`
	ExpiresAt              *int                               `json:"expiresAt,omitempty" url:"expiresAt,omitempty"`
	Revoked                bool                               `json:"revoked" url:"revoked"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReadPrivateKeyResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReadPrivateKeyResponse) GetVersion() string {
	if r == nil {
		return ""
	}
	return r.Version
}

func (r *ReadPrivateKeyResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ReadPrivateKeyResponse) GetSurfaceSlug() *string {
	if r == nil {
		return nil
	}
	return r.SurfaceSlug
}

func (r *ReadPrivateKeyResponse) GetScopes() []ReadPrivateKeyResponseScopesItem {
	if r == nil {
		return nil
	}
	return r.Scopes
}

func (r *ReadPrivateKeyResponse) GetSecondsUntilExpiration() *int {
	if r == nil {
		return nil
	}
	return r.SecondsUntilExpiration
}

func (r *ReadPrivateKeyResponse) GetExpiresAt() *int {
	if r == nil {
		return nil
	}
	return r.ExpiresAt
}

func (r *ReadPrivateKeyResponse) GetRevoked() bool {
	if r == nil {
		return false
	}
	return r.Revoked
}

func (r *ReadPrivateKeyResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReadPrivateKeyResponse) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetID(id string) {
	r.ID = id
	r.require(readPrivateKeyResponseFieldID)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetVersion(version string) {
	r.Version = version
	r.require(readPrivateKeyResponseFieldVersion)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetName(name string) {
	r.Name = name
	r.require(readPrivateKeyResponseFieldName)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetSurfaceSlug(surfaceSlug *string) {
	r.SurfaceSlug = surfaceSlug
	r.require(readPrivateKeyResponseFieldSurfaceSlug)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetScopes(scopes []ReadPrivateKeyResponseScopesItem) {
	r.Scopes = scopes
	r.require(readPrivateKeyResponseFieldScopes)
}

// SetSecondsUntilExpiration sets the SecondsUntilExpiration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetSecondsUntilExpiration(secondsUntilExpiration *int) {
	r.SecondsUntilExpiration = secondsUntilExpiration
	r.require(readPrivateKeyResponseFieldSecondsUntilExpiration)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetExpiresAt(expiresAt *int) {
	r.ExpiresAt = expiresAt
	r.require(readPrivateKeyResponseFieldExpiresAt)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadPrivateKeyResponse) SetRevoked(revoked bool) {
	r.Revoked = revoked
	r.require(readPrivateKeyResponseFieldRevoked)
}

func (r *ReadPrivateKeyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReadPrivateKeyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReadPrivateKeyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, readPrivateKeyResponseNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		r.require(presentFields)
	}
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReadPrivateKeyResponse) MarshalJSON() ([]byte, error) {
	type embed ReadPrivateKeyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReadPrivateKeyResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReadPrivateKeyResponseScopesItem string

const (
	ReadPrivateKeyResponseScopesItemOrgSurfacesRead               ReadPrivateKeyResponseScopesItem = "org:surfaces:read"
	ReadPrivateKeyResponseScopesItemOrgSurfacesWrite              ReadPrivateKeyResponseScopesItem = "org:surfaces:write"
	ReadPrivateKeyResponseScopesItemOrgSurfacesDelete             ReadPrivateKeyResponseScopesItem = "org:surfaces:delete"
	ReadPrivateKeyResponseScopesItemOrgProblemsRead               ReadPrivateKeyResponseScopesItem = "org:problems:read"
	ReadPrivateKeyResponseScopesItemOrgProblemsWrite              ReadPrivateKeyResponseScopesItem = "org:problems:write"
	ReadPrivateKeyResponseScopesItemOrgSupportRead                ReadPrivateKeyResponseScopesItem = "org:support:read"
	ReadPrivateKeyResponseScopesItemOrgSupportWrite               ReadPrivateKeyResponseScopesItem = "org:support:write"
	ReadPrivateKeyResponseScopesItemOrgReplaysRead                ReadPrivateKeyResponseScopesItem = "org:replays:read"
	ReadPrivateKeyResponseScopesItemOrgSourceContextRead          ReadPrivateKeyResponseScopesItem = "org:source_context:read"
	ReadPrivateKeyResponseScopesItemOrgIntegrationSettingsRead    ReadPrivateKeyResponseScopesItem = "org:integration_settings:read"
	ReadPrivateKeyResponseScopesItemOrgIntegrationSettingsWrite   ReadPrivateKeyResponseScopesItem = "org:integration_settings:write"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceMembersRead       ReadPrivateKeyResponseScopesItem = "org:workspace_members:read"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceMembersWrite      ReadPrivateKeyResponseScopesItem = "org:workspace_members:write"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceBillingRead       ReadPrivateKeyResponseScopesItem = "org:workspace_billing:read"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceBillingWrite      ReadPrivateKeyResponseScopesItem = "org:workspace_billing:write"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceBasicsRead        ReadPrivateKeyResponseScopesItem = "org:workspace_basics:read"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceBasicsWrite       ReadPrivateKeyResponseScopesItem = "org:workspace_basics:write"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceDomainsRead       ReadPrivateKeyResponseScopesItem = "org:workspace_domains:read"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceDomainsWrite      ReadPrivateKeyResponseScopesItem = "org:workspace_domains:write"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceAuthRead          ReadPrivateKeyResponseScopesItem = "org:workspace_auth:read"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceAuthWrite         ReadPrivateKeyResponseScopesItem = "org:workspace_auth:write"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceDestroy           ReadPrivateKeyResponseScopesItem = "org:workspace:destroy"
	ReadPrivateKeyResponseScopesItemOrgWorkspaceTransferOwnership ReadPrivateKeyResponseScopesItem = "org:workspace:transfer_ownership"
	ReadPrivateKeyResponseScopesItemReleaseWrite                  ReadPrivateKeyResponseScopesItem = "release:write"
	ReadPrivateKeyResponseScopesItemIngestWrite                   ReadPrivateKeyResponseScopesItem = "ingest:write"
)

func NewReadPrivateKeyResponseScopesItemFromString(s string) (ReadPrivateKeyResponseScopesItem, error) {
	switch s {
	case "org:surfaces:read":
		return ReadPrivateKeyResponseScopesItemOrgSurfacesRead, nil
	case "org:surfaces:write":
		return ReadPrivateKeyResponseScopesItemOrgSurfacesWrite, nil
	case "org:surfaces:delete":
		return ReadPrivateKeyResponseScopesItemOrgSurfacesDelete, nil
	case "org:problems:read":
		return ReadPrivateKeyResponseScopesItemOrgProblemsRead, nil
	case "org:problems:write":
		return ReadPrivateKeyResponseScopesItemOrgProblemsWrite, nil
	case "org:support:read":
		return ReadPrivateKeyResponseScopesItemOrgSupportRead, nil
	case "org:support:write":
		return ReadPrivateKeyResponseScopesItemOrgSupportWrite, nil
	case "org:replays:read":
		return ReadPrivateKeyResponseScopesItemOrgReplaysRead, nil
	case "org:source_context:read":
		return ReadPrivateKeyResponseScopesItemOrgSourceContextRead, nil
	case "org:integration_settings:read":
		return ReadPrivateKeyResponseScopesItemOrgIntegrationSettingsRead, nil
	case "org:integration_settings:write":
		return ReadPrivateKeyResponseScopesItemOrgIntegrationSettingsWrite, nil
	case "org:workspace_members:read":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceMembersRead, nil
	case "org:workspace_members:write":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceMembersWrite, nil
	case "org:workspace_billing:read":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceBillingRead, nil
	case "org:workspace_billing:write":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceBillingWrite, nil
	case "org:workspace_basics:read":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceBasicsRead, nil
	case "org:workspace_basics:write":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceBasicsWrite, nil
	case "org:workspace_domains:read":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceDomainsRead, nil
	case "org:workspace_domains:write":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceDomainsWrite, nil
	case "org:workspace_auth:read":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceAuthRead, nil
	case "org:workspace_auth:write":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceAuthWrite, nil
	case "org:workspace:destroy":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceDestroy, nil
	case "org:workspace:transfer_ownership":
		return ReadPrivateKeyResponseScopesItemOrgWorkspaceTransferOwnership, nil
	case "release:write":
		return ReadPrivateKeyResponseScopesItemReleaseWrite, nil
	case "ingest:write":
		return ReadPrivateKeyResponseScopesItemIngestWrite, nil
	}
	var t ReadPrivateKeyResponseScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReadPrivateKeyResponseScopesItem) Ptr() *ReadPrivateKeyResponseScopesItem {
	return &r
}

var (
	revokeWorkspaceAPIKeyResponseFieldSuccess = big.NewInt(1 << 0)
)

type RevokeWorkspaceAPIKeyResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeWorkspaceAPIKeyResponse) GetSuccess() bool {
	if r == nil {
		return false
	}
	return r.Success
}

func (r *RevokeWorkspaceAPIKeyResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RevokeWorkspaceAPIKeyResponse) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeWorkspaceAPIKeyResponse) SetSuccess(success bool) {
	r.Success = success
	r.require(revokeWorkspaceAPIKeyResponseFieldSuccess)
}

func (r *RevokeWorkspaceAPIKeyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeWorkspaceAPIKeyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeWorkspaceAPIKeyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeWorkspaceAPIKeyResponse) MarshalJSON() ([]byte, error) {
	type embed RevokeWorkspaceAPIKeyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RevokeWorkspaceAPIKeyResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type CreateWorkspaceAPIKeyRequestScopesItem string

const (
	CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesRead               CreateWorkspaceAPIKeyRequestScopesItem = "org:surfaces:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesWrite              CreateWorkspaceAPIKeyRequestScopesItem = "org:surfaces:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesDelete             CreateWorkspaceAPIKeyRequestScopesItem = "org:surfaces:delete"
	CreateWorkspaceAPIKeyRequestScopesItemOrgProblemsRead               CreateWorkspaceAPIKeyRequestScopesItem = "org:problems:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgProblemsWrite              CreateWorkspaceAPIKeyRequestScopesItem = "org:problems:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgSupportRead                CreateWorkspaceAPIKeyRequestScopesItem = "org:support:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgSupportWrite               CreateWorkspaceAPIKeyRequestScopesItem = "org:support:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgReplaysRead                CreateWorkspaceAPIKeyRequestScopesItem = "org:replays:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgSourceContextRead          CreateWorkspaceAPIKeyRequestScopesItem = "org:source_context:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgIntegrationSettingsRead    CreateWorkspaceAPIKeyRequestScopesItem = "org:integration_settings:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgIntegrationSettingsWrite   CreateWorkspaceAPIKeyRequestScopesItem = "org:integration_settings:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceMembersRead       CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_members:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceMembersWrite      CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_members:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBillingRead       CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_billing:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBillingWrite      CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_billing:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBasicsRead        CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_basics:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBasicsWrite       CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_basics:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceDomainsRead       CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_domains:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceDomainsWrite      CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_domains:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceAuthRead          CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_auth:read"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceAuthWrite         CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace_auth:write"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceDestroy           CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace:destroy"
	CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceTransferOwnership CreateWorkspaceAPIKeyRequestScopesItem = "org:workspace:transfer_ownership"
	CreateWorkspaceAPIKeyRequestScopesItemReleaseWrite                  CreateWorkspaceAPIKeyRequestScopesItem = "release:write"
	CreateWorkspaceAPIKeyRequestScopesItemIngestWrite                   CreateWorkspaceAPIKeyRequestScopesItem = "ingest:write"
)

func NewCreateWorkspaceAPIKeyRequestScopesItemFromString(s string) (CreateWorkspaceAPIKeyRequestScopesItem, error) {
	switch s {
	case "org:surfaces:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesRead, nil
	case "org:surfaces:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesWrite, nil
	case "org:surfaces:delete":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesDelete, nil
	case "org:problems:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgProblemsRead, nil
	case "org:problems:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgProblemsWrite, nil
	case "org:support:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgSupportRead, nil
	case "org:support:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgSupportWrite, nil
	case "org:replays:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgReplaysRead, nil
	case "org:source_context:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgSourceContextRead, nil
	case "org:integration_settings:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgIntegrationSettingsRead, nil
	case "org:integration_settings:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgIntegrationSettingsWrite, nil
	case "org:workspace_members:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceMembersRead, nil
	case "org:workspace_members:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceMembersWrite, nil
	case "org:workspace_billing:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBillingRead, nil
	case "org:workspace_billing:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBillingWrite, nil
	case "org:workspace_basics:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBasicsRead, nil
	case "org:workspace_basics:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceBasicsWrite, nil
	case "org:workspace_domains:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceDomainsRead, nil
	case "org:workspace_domains:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceDomainsWrite, nil
	case "org:workspace_auth:read":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceAuthRead, nil
	case "org:workspace_auth:write":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceAuthWrite, nil
	case "org:workspace:destroy":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceDestroy, nil
	case "org:workspace:transfer_ownership":
		return CreateWorkspaceAPIKeyRequestScopesItemOrgWorkspaceTransferOwnership, nil
	case "release:write":
		return CreateWorkspaceAPIKeyRequestScopesItemReleaseWrite, nil
	case "ingest:write":
		return CreateWorkspaceAPIKeyRequestScopesItemIngestWrite, nil
	}
	var t CreateWorkspaceAPIKeyRequestScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateWorkspaceAPIKeyRequestScopesItem) Ptr() *CreateWorkspaceAPIKeyRequestScopesItem {
	return &c
}

var (
	mutationOrganizationsUpdateBasicsRequestArgsFieldName = big.NewInt(1 << 0)
	mutationOrganizationsUpdateBasicsRequestArgsFieldSlug = big.NewInt(1 << 1)
)

type MutationOrganizationsUpdateBasicsRequestArgs struct {
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) GetSlug() *string {
	if m == nil {
		return nil
	}
	return m.Slug
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsUpdateBasicsRequestArgs) SetName(name *string) {
	m.Name = name
	m.require(mutationOrganizationsUpdateBasicsRequestArgsFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsUpdateBasicsRequestArgs) SetSlug(slug *string) {
	m.Slug = slug
	m.require(mutationOrganizationsUpdateBasicsRequestArgsFieldSlug)
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationOrganizationsUpdateBasicsRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationOrganizationsUpdateBasicsRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) MarshalJSON() ([]byte, error) {
	type embed MutationOrganizationsUpdateBasicsRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationOrganizationsUpdateBasicsRequestArgs) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationSurfacesDeleteRequestArgsFieldSurfaceSlug = big.NewInt(1 << 0)
)

type MutationSurfacesDeleteRequestArgs struct {
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationSurfacesDeleteRequestArgs) GetSurfaceSlug() string {
	if m == nil {
		return ""
	}
	return m.SurfaceSlug
}

func (m *MutationSurfacesDeleteRequestArgs) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationSurfacesDeleteRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesDeleteRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	m.SurfaceSlug = surfaceSlug
	m.require(mutationSurfacesDeleteRequestArgsFieldSurfaceSlug)
}

func (m *MutationSurfacesDeleteRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationSurfacesDeleteRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationSurfacesDeleteRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationSurfacesDeleteRequestArgs) MarshalJSON() ([]byte, error) {
	type embed MutationSurfacesDeleteRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationSurfacesDeleteRequestArgs) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationSurfacesUpdateNameRequestArgsFieldName        = big.NewInt(1 << 0)
	mutationSurfacesUpdateNameRequestArgsFieldSurfaceSlug = big.NewInt(1 << 1)
)

type MutationSurfacesUpdateNameRequestArgs struct {
	Name        string `json:"name" url:"name"`
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationSurfacesUpdateNameRequestArgs) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MutationSurfacesUpdateNameRequestArgs) GetSurfaceSlug() string {
	if m == nil {
		return ""
	}
	return m.SurfaceSlug
}

func (m *MutationSurfacesUpdateNameRequestArgs) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationSurfacesUpdateNameRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesUpdateNameRequestArgs) SetName(name string) {
	m.Name = name
	m.require(mutationSurfacesUpdateNameRequestArgsFieldName)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationSurfacesUpdateNameRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	m.SurfaceSlug = surfaceSlug
	m.require(mutationSurfacesUpdateNameRequestArgsFieldSurfaceSlug)
}

func (m *MutationSurfacesUpdateNameRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationSurfacesUpdateNameRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationSurfacesUpdateNameRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationSurfacesUpdateNameRequestArgs) MarshalJSON() ([]byte, error) {
	type embed MutationSurfacesUpdateNameRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationSurfacesUpdateNameRequestArgs) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	querySurfacesGetBySlugIncludeDeletedRequestArgsFieldSurfaceSlug = big.NewInt(1 << 0)
)

type QuerySurfacesGetBySlugIncludeDeletedRequestArgs struct {
	SurfaceSlug string `json:"surfaceSlug" url:"surfaceSlug"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) GetSurfaceSlug() string {
	if q == nil {
		return ""
	}
	return q.SurfaceSlug
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) SetSurfaceSlug(surfaceSlug string) {
	q.SurfaceSlug = surfaceSlug
	q.require(querySurfacesGetBySlugIncludeDeletedRequestArgsFieldSurfaceSlug)
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler QuerySurfacesGetBySlugIncludeDeletedRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuerySurfacesGetBySlugIncludeDeletedRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) MarshalJSON() ([]byte, error) {
	type embed QuerySurfacesGetBySlugIncludeDeletedRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuerySurfacesGetBySlugIncludeDeletedRequestArgs) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}
