// Code generated by Fern. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	addProxyDomainWorkspacesRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	addProxyDomainWorkspacesRequestFieldArgs          = big.NewInt(1 << 1)
)

type AddProxyDomainWorkspacesRequest struct {
	WorkspaceSlug string                               `json:"-" url:"-"`
	Args          *AddProxyDomainWorkspacesRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddProxyDomainWorkspacesRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddProxyDomainWorkspacesRequest) SetWorkspaceSlug(workspaceSlug string) {
	a.WorkspaceSlug = workspaceSlug
	a.require(addProxyDomainWorkspacesRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddProxyDomainWorkspacesRequest) SetArgs(args *AddProxyDomainWorkspacesRequestArgs) {
	a.Args = args
	a.require(addProxyDomainWorkspacesRequestFieldArgs)
}

func (a *AddProxyDomainWorkspacesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AddProxyDomainWorkspacesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AddProxyDomainWorkspacesRequest(body)
	return nil
}

func (a *AddProxyDomainWorkspacesRequest) MarshalJSON() ([]byte, error) {
	type embed AddProxyDomainWorkspacesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	currentWorkspacesRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	currentWorkspacesRequestFieldArgs          = big.NewInt(1 << 1)
)

type CurrentWorkspacesRequest struct {
	WorkspaceSlug string         `json:"-" url:"-"`
	Args          map[string]any `json:"args,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CurrentWorkspacesRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentWorkspacesRequest) SetWorkspaceSlug(workspaceSlug string) {
	c.WorkspaceSlug = workspaceSlug
	c.require(currentWorkspacesRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentWorkspacesRequest) SetArgs(args map[string]any) {
	c.Args = args
	c.require(currentWorkspacesRequestFieldArgs)
}

func (c *CurrentWorkspacesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CurrentWorkspacesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CurrentWorkspacesRequest(body)
	return nil
}

func (c *CurrentWorkspacesRequest) MarshalJSON() ([]byte, error) {
	type embed CurrentWorkspacesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	removeProxyDomainWorkspacesRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	removeProxyDomainWorkspacesRequestFieldArgs          = big.NewInt(1 << 1)
)

type RemoveProxyDomainWorkspacesRequest struct {
	WorkspaceSlug string                                  `json:"-" url:"-"`
	Args          *RemoveProxyDomainWorkspacesRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoveProxyDomainWorkspacesRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveProxyDomainWorkspacesRequest) SetWorkspaceSlug(workspaceSlug string) {
	r.WorkspaceSlug = workspaceSlug
	r.require(removeProxyDomainWorkspacesRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveProxyDomainWorkspacesRequest) SetArgs(args *RemoveProxyDomainWorkspacesRequestArgs) {
	r.Args = args
	r.require(removeProxyDomainWorkspacesRequestFieldArgs)
}

func (r *RemoveProxyDomainWorkspacesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoveProxyDomainWorkspacesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RemoveProxyDomainWorkspacesRequest(body)
	return nil
}

func (r *RemoveProxyDomainWorkspacesRequest) MarshalJSON() ([]byte, error) {
	type embed RemoveProxyDomainWorkspacesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mutationOrganizationsAddProxyDomainResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationOrganizationsAddProxyDomainResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationOrganizationsAddProxyDomainResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationOrganizationsAddProxyDomainResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationOrganizationsAddProxyDomainResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsAddProxyDomainResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationOrganizationsAddProxyDomainResponseFieldSuccess)
}

func (m *MutationOrganizationsAddProxyDomainResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationOrganizationsAddProxyDomainResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationOrganizationsAddProxyDomainResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationOrganizationsAddProxyDomainResponse) MarshalJSON() ([]byte, error) {
	type embed MutationOrganizationsAddProxyDomainResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationOrganizationsAddProxyDomainResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationOrganizationsRemoveProxyDomainResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationOrganizationsRemoveProxyDomainResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationOrganizationsRemoveProxyDomainResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationOrganizationsRemoveProxyDomainResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationOrganizationsRemoveProxyDomainResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsRemoveProxyDomainResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationOrganizationsRemoveProxyDomainResponseFieldSuccess)
}

func (m *MutationOrganizationsRemoveProxyDomainResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationOrganizationsRemoveProxyDomainResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationOrganizationsRemoveProxyDomainResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationOrganizationsRemoveProxyDomainResponse) MarshalJSON() ([]byte, error) {
	type embed MutationOrganizationsRemoveProxyDomainResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationOrganizationsRemoveProxyDomainResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mutationOrganizationsUpdateBasicsResponseFieldSuccess = big.NewInt(1 << 0)
)

type MutationOrganizationsUpdateBasicsResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutationOrganizationsUpdateBasicsResponse) GetSuccess() bool {
	if m == nil {
		return false
	}
	return m.Success
}

func (m *MutationOrganizationsUpdateBasicsResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MutationOrganizationsUpdateBasicsResponse) require(field *big.Int) {
	next := new(big.Int)
	if m.explicitFields != nil {
		next.Set(m.explicitFields)
	}
	next.Or(next, field)
	m.explicitFields = next
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MutationOrganizationsUpdateBasicsResponse) SetSuccess(success bool) {
	m.Success = success
	m.require(mutationOrganizationsUpdateBasicsResponseFieldSuccess)
}

func (m *MutationOrganizationsUpdateBasicsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MutationOrganizationsUpdateBasicsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutationOrganizationsUpdateBasicsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutationOrganizationsUpdateBasicsResponse) MarshalJSON() ([]byte, error) {
	type embed MutationOrganizationsUpdateBasicsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MutationOrganizationsUpdateBasicsResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	queryOrganizationsCurrentResponseFieldID                    = big.NewInt(1 << 0)
	queryOrganizationsCurrentResponseFieldName                  = big.NewInt(1 << 1)
	queryOrganizationsCurrentResponseFieldSlug                  = big.NewInt(1 << 2)
	queryOrganizationsCurrentResponseFieldDataResidencyLocation = big.NewInt(1 << 3)
)

type QueryOrganizationsCurrentResponse struct {
	ID                    string                                                 `json:"id" url:"id"`
	Name                  string                                                 `json:"name" url:"name"`
	Slug                  string                                                 `json:"slug" url:"slug"`
	DataResidencyLocation QueryOrganizationsCurrentResponseDataResidencyLocation `json:"dataResidencyLocation" url:"dataResidencyLocation"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (q *QueryOrganizationsCurrentResponse) GetID() string {
	if q == nil {
		return ""
	}
	return q.ID
}

func (q *QueryOrganizationsCurrentResponse) GetName() string {
	if q == nil {
		return ""
	}
	return q.Name
}

func (q *QueryOrganizationsCurrentResponse) GetSlug() string {
	if q == nil {
		return ""
	}
	return q.Slug
}

func (q *QueryOrganizationsCurrentResponse) GetDataResidencyLocation() QueryOrganizationsCurrentResponseDataResidencyLocation {
	if q == nil {
		return ""
	}
	return q.DataResidencyLocation
}

func (q *QueryOrganizationsCurrentResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.ExtraProperties
}

func (q *QueryOrganizationsCurrentResponse) require(field *big.Int) {
	next := new(big.Int)
	if q.explicitFields != nil {
		next.Set(q.explicitFields)
	}
	next.Or(next, field)
	q.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetID(id string) {
	q.ID = id
	q.require(queryOrganizationsCurrentResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetName(name string) {
	q.Name = name
	q.require(queryOrganizationsCurrentResponseFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetSlug(slug string) {
	q.Slug = slug
	q.require(queryOrganizationsCurrentResponseFieldSlug)
}

// SetDataResidencyLocation sets the DataResidencyLocation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueryOrganizationsCurrentResponse) SetDataResidencyLocation(dataResidencyLocation QueryOrganizationsCurrentResponseDataResidencyLocation) {
	q.DataResidencyLocation = dataResidencyLocation
	q.require(queryOrganizationsCurrentResponseFieldDataResidencyLocation)
}

func (q *QueryOrganizationsCurrentResponse) UnmarshalJSON(data []byte) error {
	type embed QueryOrganizationsCurrentResponse
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QueryOrganizationsCurrentResponse(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.ExtraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueryOrganizationsCurrentResponse) MarshalJSON() ([]byte, error) {
	type embed QueryOrganizationsCurrentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, q.ExtraProperties)
}

func (q *QueryOrganizationsCurrentResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

type QueryOrganizationsCurrentResponseDataResidencyLocation string

const (
	QueryOrganizationsCurrentResponseDataResidencyLocationUs QueryOrganizationsCurrentResponseDataResidencyLocation = "us"
	QueryOrganizationsCurrentResponseDataResidencyLocationEu QueryOrganizationsCurrentResponseDataResidencyLocation = "eu"
)

func NewQueryOrganizationsCurrentResponseDataResidencyLocationFromString(s string) (QueryOrganizationsCurrentResponseDataResidencyLocation, error) {
	switch s {
	case "us":
		return QueryOrganizationsCurrentResponseDataResidencyLocationUs, nil
	case "eu":
		return QueryOrganizationsCurrentResponseDataResidencyLocationEu, nil
	}
	var t QueryOrganizationsCurrentResponseDataResidencyLocation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QueryOrganizationsCurrentResponseDataResidencyLocation) Ptr() *QueryOrganizationsCurrentResponseDataResidencyLocation {
	return &q
}

var (
	addProxyDomainWorkspacesRequestArgsFieldID   = big.NewInt(1 << 0)
	addProxyDomainWorkspacesRequestArgsFieldName = big.NewInt(1 << 1)
)

type AddProxyDomainWorkspacesRequestArgs struct {
	ID   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddProxyDomainWorkspacesRequestArgs) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AddProxyDomainWorkspacesRequestArgs) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AddProxyDomainWorkspacesRequestArgs) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AddProxyDomainWorkspacesRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddProxyDomainWorkspacesRequestArgs) SetID(id string) {
	a.ID = id
	a.require(addProxyDomainWorkspacesRequestArgsFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddProxyDomainWorkspacesRequestArgs) SetName(name string) {
	a.Name = name
	a.require(addProxyDomainWorkspacesRequestArgsFieldName)
}

func (a *AddProxyDomainWorkspacesRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler AddProxyDomainWorkspacesRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddProxyDomainWorkspacesRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddProxyDomainWorkspacesRequestArgs) MarshalJSON() ([]byte, error) {
	type embed AddProxyDomainWorkspacesRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddProxyDomainWorkspacesRequestArgs) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	removeProxyDomainWorkspacesRequestArgsFieldID   = big.NewInt(1 << 0)
	removeProxyDomainWorkspacesRequestArgsFieldName = big.NewInt(1 << 1)
)

type RemoveProxyDomainWorkspacesRequestArgs struct {
	ID   *string `json:"id,omitempty" url:"id,omitempty"`
	Name string  `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveProxyDomainWorkspacesRequestArgs) SetID(id *string) {
	r.ID = id
	r.require(removeProxyDomainWorkspacesRequestArgsFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveProxyDomainWorkspacesRequestArgs) SetName(name string) {
	r.Name = name
	r.require(removeProxyDomainWorkspacesRequestArgsFieldName)
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoveProxyDomainWorkspacesRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RemoveProxyDomainWorkspacesRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) MarshalJSON() ([]byte, error) {
	type embed RemoveProxyDomainWorkspacesRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemoveProxyDomainWorkspacesRequestArgs) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	updateBasicsWorkspacesRequestArgsFieldName = big.NewInt(1 << 0)
	updateBasicsWorkspacesRequestArgsFieldSlug = big.NewInt(1 << 1)
)

type UpdateBasicsWorkspacesRequestArgs struct {
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateBasicsWorkspacesRequestArgs) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateBasicsWorkspacesRequestArgs) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

func (u *UpdateBasicsWorkspacesRequestArgs) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateBasicsWorkspacesRequestArgs) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBasicsWorkspacesRequestArgs) SetName(name *string) {
	u.Name = name
	u.require(updateBasicsWorkspacesRequestArgsFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBasicsWorkspacesRequestArgs) SetSlug(slug *string) {
	u.Slug = slug
	u.require(updateBasicsWorkspacesRequestArgsFieldSlug)
}

func (u *UpdateBasicsWorkspacesRequestArgs) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateBasicsWorkspacesRequestArgs
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateBasicsWorkspacesRequestArgs(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateBasicsWorkspacesRequestArgs) MarshalJSON() ([]byte, error) {
	type embed UpdateBasicsWorkspacesRequestArgs
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateBasicsWorkspacesRequestArgs) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateBasicsWorkspacesRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	updateBasicsWorkspacesRequestFieldArgs          = big.NewInt(1 << 1)
)

type UpdateBasicsWorkspacesRequest struct {
	WorkspaceSlug string                             `json:"-" url:"-"`
	Args          *UpdateBasicsWorkspacesRequestArgs `json:"args" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateBasicsWorkspacesRequest) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBasicsWorkspacesRequest) SetWorkspaceSlug(workspaceSlug string) {
	u.WorkspaceSlug = workspaceSlug
	u.require(updateBasicsWorkspacesRequestFieldWorkspaceSlug)
}

// SetArgs sets the Args field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBasicsWorkspacesRequest) SetArgs(args *UpdateBasicsWorkspacesRequestArgs) {
	u.Args = args
	u.require(updateBasicsWorkspacesRequestFieldArgs)
}

func (u *UpdateBasicsWorkspacesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateBasicsWorkspacesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateBasicsWorkspacesRequest(body)
	return nil
}

func (u *UpdateBasicsWorkspacesRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateBasicsWorkspacesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
