// Code generated by Fern. DO NOT EDIT.

package workspaces_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    client "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/client"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func VerifyAuthHeaders(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    headerMatchers map[string]string,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}`)
    for name, matcher := range headerMatchers {
        reqBody.WriteString(`,"`)
        reqBody.WriteString(name)
        reqBody.WriteString(`":`)
        reqBody.WriteString(matcher)
    }
    reqBody.WriteString(`}}`)
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, 1, len(result.Requests), "expected exactly one request with the routed auth headers for "+testId)
}

func TestWorkspacesQueryOrganizationsCurrentWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.QueryOrganizationsCurrentRequest{
            WorkspaceSlug: "workspaceSlug",
        }
    _, invocationErr :=     client.Workspaces.QueryOrganizationsCurrent(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesQueryOrganizationsCurrentWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesQueryOrganizationsCurrentWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/organizations.current", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesQueryOrganizationsCurrentWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/organizations.current", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesQuerySurfacesGetBySlugIncludeDeletedWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.QuerySurfacesGetBySlugIncludeDeletedRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.QuerySurfacesGetBySlugIncludeDeletedRequestArgs{
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Workspaces.QuerySurfacesGetBySlugIncludeDeleted(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesQuerySurfacesGetBySlugIncludeDeletedWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesQuerySurfacesGetBySlugIncludeDeletedWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/surfaces.getBySlugIncludeDeleted", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesQuerySurfacesGetBySlugIncludeDeletedWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/surfaces.getBySlugIncludeDeleted", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesMutationOrganizationsUpdateBasicsWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.MutationOrganizationsUpdateBasicsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.MutationOrganizationsUpdateBasicsRequestArgs{},
        }
    _, invocationErr :=     client.Workspaces.MutationOrganizationsUpdateBasics(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesMutationOrganizationsUpdateBasicsWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesMutationOrganizationsUpdateBasicsWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/organizations.updateBasics", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesMutationOrganizationsUpdateBasicsWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/organizations.updateBasics", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesMutationSurfacesDeleteWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.MutationSurfacesDeleteRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.MutationSurfacesDeleteRequestArgs{
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Workspaces.MutationSurfacesDelete(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesMutationSurfacesDeleteWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesMutationSurfacesDeleteWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.delete", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesMutationSurfacesDeleteWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.delete", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesMutationSurfacesUpdateNameWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.MutationSurfacesUpdateNameRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.MutationSurfacesUpdateNameRequestArgs{
                Name: "name",
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Workspaces.MutationSurfacesUpdateName(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesMutationSurfacesUpdateNameWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesMutationSurfacesUpdateNameWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.updateName", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesMutationSurfacesUpdateNameWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.updateName", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesCreateWorkspaceAPIKeyWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.CreateWorkspaceAPIKeyRequest{
            WorkspaceSlug: "workspaceSlug",
            IdempotencyKey: "idempotencyKey",
            Name: "name",
            Scopes: []sdk.CreateWorkspaceAPIKeyRequestScopesItem{
                sdk.CreateWorkspaceAPIKeyRequestScopesItemOrgSurfacesRead,
            },
        }
    _, invocationErr :=     client.Workspaces.CreateWorkspaceAPIKey(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesCreateWorkspaceAPIKeyWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesCreateWorkspaceAPIKeyWithWireMock", "POST", "/v3/workspaces/workspaceSlug/api-keys", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesCreateWorkspaceAPIKeyWithWireMock", "POST", "/v3/workspaces/workspaceSlug/api-keys", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesReadPrivateKeyWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.ReadPrivateKeyRequest{
            WorkspaceSlug: "workspaceSlug",
            APIKeyID: "apiKeyId",
        }
    _, invocationErr :=     client.Workspaces.ReadPrivateKey(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesReadPrivateKeyWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesReadPrivateKeyWithWireMock", "GET", "/v3/workspaces/workspaceSlug/api-keys/apiKeyId", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesReadPrivateKeyWithWireMock", "GET", "/v3/workspaces/workspaceSlug/api-keys/apiKeyId", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestWorkspacesRevokeWorkspaceAPIKeyWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.RevokeWorkspaceAPIKeyRequest{
            WorkspaceSlug: "workspaceSlug",
            APIKeyID: "apiKeyId",
        }
    _, invocationErr :=     client.Workspaces.RevokeWorkspaceAPIKey(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWorkspacesRevokeWorkspaceAPIKeyWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWorkspacesRevokeWorkspaceAPIKeyWithWireMock", "DELETE", "/v3/workspaces/workspaceSlug/api-keys/apiKeyId", nil, 1)
    VerifyAuthHeaders(t, "TestWorkspacesRevokeWorkspaceAPIKeyWithWireMock", "DELETE", "/v3/workspaces/workspaceSlug/api-keys/apiKeyId", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}


