// Code generated by Fern. DO NOT EDIT.

package surfaces

import (
    context "context"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Creates a surface in the workspace. Reuse the original request identity when retrying the same creation attempt.
// 
// Example:
// 
// 	request := &sdk.CreateSurfaceRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    APIKey: &sdk.CreateSurfaceRequestAPIKey{
// 	        Scopes: []sdk.CreateSurfaceRequestAPIKeyScopesItem{
// 	            sdk.CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesRead,
// 	        },
// 	    },
// 	    IdempotencyKey: "idempotencyKey",
// 	    Name: "name",
// 	    Type: sdk.CreateSurfaceRequestTypeElysia,
// 	}
// 	client.Surfaces.CreateSurface(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) CreateSurface(
    ctx context.Context,
    request *sdk.CreateSurfaceRequest,
    opts ...option.RequestOption,
) (*sdk.CreateSurfaceResponse, error){
    response, err := c.WithRawResponse.CreateSurface(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

