// Code generated by Fern. DO NOT EDIT.

package surfaces_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    client "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/client"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func VerifyAuthHeaders(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    headerMatchers map[string]string,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}`)
    for name, matcher := range headerMatchers {
        reqBody.WriteString(`,"`)
        reqBody.WriteString(name)
        reqBody.WriteString(`":`)
        reqBody.WriteString(matcher)
    }
    reqBody.WriteString(`}}`)
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, 1, len(result.Requests), "expected exactly one request with the routed auth headers for "+testId)
}

func TestSurfacesGetBySlugIncludeDeletedWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.GetBySlugIncludeDeletedSurfacesRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.GetBySlugIncludeDeletedSurfacesRequestArgs{
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Surfaces.GetBySlugIncludeDeleted(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestSurfacesGetBySlugIncludeDeletedWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestSurfacesGetBySlugIncludeDeletedWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/surfaces.getBySlugIncludeDeleted", nil, 1)
    VerifyAuthHeaders(t, "TestSurfacesGetBySlugIncludeDeletedWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/surfaces.getBySlugIncludeDeleted", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestSurfacesDeleteWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.DeleteSurfacesRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.DeleteSurfacesRequestArgs{
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Surfaces.Delete(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestSurfacesDeleteWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestSurfacesDeleteWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.delete", nil, 1)
    VerifyAuthHeaders(t, "TestSurfacesDeleteWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.delete", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestSurfacesSetAnonymousUserTrackingWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.SetAnonymousUserTrackingSurfacesRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.SetAnonymousUserTrackingSurfacesRequestArgs{
                SurfaceSlug: "surfaceSlug",
                Enabled: true,
            },
        }
    _, invocationErr :=     client.Surfaces.SetAnonymousUserTracking(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestSurfacesSetAnonymousUserTrackingWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestSurfacesSetAnonymousUserTrackingWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.setAnonymousUserTracking", nil, 1)
    VerifyAuthHeaders(t, "TestSurfacesSetAnonymousUserTrackingWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.setAnonymousUserTracking", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestSurfacesUpdateNameWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.UpdateNameSurfacesRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.UpdateNameSurfacesRequestArgs{
                Name: "name",
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Surfaces.UpdateName(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestSurfacesUpdateNameWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestSurfacesUpdateNameWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.updateName", nil, 1)
    VerifyAuthHeaders(t, "TestSurfacesUpdateNameWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/surfaces.updateName", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestSurfacesCreateSurfaceWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.CreateSurfaceRequest{
            WorkspaceSlug: "workspaceSlug",
            APIKey: &sdk.CreateSurfaceRequestAPIKey{
                Scopes: []sdk.CreateSurfaceRequestAPIKeyScopesItem{
                    sdk.CreateSurfaceRequestAPIKeyScopesItemOrgSurfacesRead,
                },
            },
            IdempotencyKey: "idempotencyKey",
            Name: "name",
            Type: sdk.CreateSurfaceRequestTypeElysia,
        }
    _, invocationErr :=     client.Surfaces.CreateSurface(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestSurfacesCreateSurfaceWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestSurfacesCreateSurfaceWithWireMock", "POST", "/v3/workspaces/workspaceSlug/surfaces", nil, 1)
    VerifyAuthHeaders(t, "TestSurfacesCreateSurfaceWithWireMock", "POST", "/v3/workspaces/workspaceSlug/surfaces", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}


