// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_private_key

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PrivateKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"secret": schema.StringAttribute{
						Computed:            true,
						Description:         "Private API credential returned only on creation.",
						MarkdownDescription: "Private API credential returned only on creation.",
					},
				},
				CustomType: ApiKeyType{
					ObjectType: types.ObjectType{
						AttrTypes: ApiKeyValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"expires_at": schema.Int64Attribute{
				Computed:            true,
				Description:         "Expiration as Unix milliseconds, or null for no expiry.",
				MarkdownDescription: "Expiration as Unix milliseconds, or null for no expiry.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Stable private key identifier.",
				MarkdownDescription: "Stable private key identifier.",
			},
			"idempotency_key": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Display name of the key.",
				MarkdownDescription: "Display name of the key.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 64),
				},
			},
			"scopes": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "Permission scopes granted to the key.",
				MarkdownDescription: "Permission scopes granted to the key.",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
			},
			"seconds_until_expiration": schema.Int64Attribute{
				Required:            true,
				Description:         "Positive lifetime in seconds, or null for no expiry.",
				MarkdownDescription: "Positive lifetime in seconds, or null for no expiry.",
				Validators: []validator.Int64{
					int64validator.Between(-9007199254740991, 9007199254740991),
				},
			},
			"surface_slug": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Surface URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Surface URL slug, using lowercase letters, numbers, and hyphens.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
			"version": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the currently active key version.",
				MarkdownDescription: "Identifier of the currently active key version.",
			},
			"workspace_slug": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type PrivateKeyModel struct {
	ApiKey                 ApiKeyValue  `tfsdk:"api_key"`
	ExpiresAt              types.Int64  `tfsdk:"expires_at"`
	Id                     types.String `tfsdk:"id"`
	IdempotencyKey         types.String `tfsdk:"idempotency_key"`
	Name                   types.String `tfsdk:"name"`
	Scopes                 types.List   `tfsdk:"scopes"`
	SecondsUntilExpiration types.Int64  `tfsdk:"seconds_until_expiration"`
	SurfaceSlug            types.String `tfsdk:"surface_slug"`
	Version                types.String `tfsdk:"version"`
	WorkspaceSlug          types.String `tfsdk:"workspace_slug"`
}

var _ basetypes.ObjectTypable = ApiKeyType{}

type ApiKeyType struct {
	basetypes.ObjectType
}

func (t ApiKeyType) Equal(o attr.Type) bool {
	other, ok := o.(ApiKeyType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ApiKeyType) String() string {
	return "ApiKeyType"
}

func (t ApiKeyType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	secretAttribute, ok := attributes["secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`secret is missing from object`)

		return nil, diags
	}

	secretVal, ok := secretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`secret expected to be basetypes.StringValue, was: %T`, secretAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ApiKeyValue{
		Secret: secretVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewApiKeyValueNull() ApiKeyValue {
	return ApiKeyValue{
		state: attr.ValueStateNull,
	}
}

func NewApiKeyValueUnknown() ApiKeyValue {
	return ApiKeyValue{
		state: attr.ValueStateUnknown,
	}
}

func NewApiKeyValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ApiKeyValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ApiKeyValue Attribute Value",
				"While creating a ApiKeyValue value, a missing attribute value was detected. "+
					"A ApiKeyValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ApiKeyValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ApiKeyValue Attribute Type",
				"While creating a ApiKeyValue value, an invalid attribute value was detected. "+
					"A ApiKeyValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ApiKeyValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ApiKeyValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ApiKeyValue Attribute Value",
				"While creating a ApiKeyValue value, an extra attribute value was detected. "+
					"A ApiKeyValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ApiKeyValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewApiKeyValueUnknown(), diags
	}

	secretAttribute, ok := attributes["secret"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`secret is missing from object`)

		return NewApiKeyValueUnknown(), diags
	}

	secretVal, ok := secretAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`secret expected to be basetypes.StringValue, was: %T`, secretAttribute))
	}

	if diags.HasError() {
		return NewApiKeyValueUnknown(), diags
	}

	return ApiKeyValue{
		Secret: secretVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewApiKeyValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ApiKeyValue {
	object, diags := NewApiKeyValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewApiKeyValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ApiKeyType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewApiKeyValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewApiKeyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewApiKeyValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewApiKeyValueMust(ApiKeyValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ApiKeyType) ValueType(ctx context.Context) attr.Value {
	return ApiKeyValue{}
}

var _ basetypes.ObjectValuable = ApiKeyValue{}

type ApiKeyValue struct {
	Secret basetypes.StringValue `tfsdk:"secret"`
	state  attr.ValueState
}

func (v ApiKeyValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["secret"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Secret.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["secret"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ApiKeyValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ApiKeyValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ApiKeyValue) String() string {
	return "ApiKeyValue"
}

func (v ApiKeyValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"secret": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"secret": v.Secret,
		})

	return objVal, diags
}

func (v ApiKeyValue) Equal(o attr.Value) bool {
	other, ok := o.(ApiKeyValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Secret.Equal(other.Secret) {
		return false
	}

	return true
}

func (v ApiKeyValue) Type(ctx context.Context) attr.Type {
	return ApiKeyType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ApiKeyValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"secret": basetypes.StringType{},
	}
}
