// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_workspace

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func WorkspaceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data_residency_location": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"workspace_slug": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type WorkspaceModel struct {
	DataResidencyLocation types.String `tfsdk:"data_residency_location"`
	Id                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	WorkspaceSlug         types.String `tfsdk:"workspace_slug"`
}
