// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tracking_domain

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TrackingDomainResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"domain_metadata": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"cf_ssl_status": schema.StringAttribute{
						Computed:            true,
						Description:         "Current TLS certificate provisioning status.",
						MarkdownDescription: "Current TLS certificate provisioning status.",
					},
				},
				CustomType: DomainMetadataType{
					ObjectType: types.ObjectType{
						AttrTypes: DomainMetadataValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique tracking domain identifier.",
				MarkdownDescription: "Unique tracking domain identifier.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Lowercase fully qualified tracking hostname, without a trailing dot.",
				MarkdownDescription: "Lowercase fully qualified tracking hostname, without a trailing dot.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Current hostname verification status.",
				MarkdownDescription: "Current hostname verification status.",
			},
			"workspace_slug": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type TrackingDomainModel struct {
	DomainMetadata DomainMetadataValue `tfsdk:"domain_metadata"`
	Id             types.String        `tfsdk:"id"`
	Name           types.String        `tfsdk:"name"`
	Status         types.String        `tfsdk:"status"`
	WorkspaceSlug  types.String        `tfsdk:"workspace_slug"`
}

var _ basetypes.ObjectTypable = DomainMetadataType{}

type DomainMetadataType struct {
	basetypes.ObjectType
}

func (t DomainMetadataType) Equal(o attr.Type) bool {
	other, ok := o.(DomainMetadataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DomainMetadataType) String() string {
	return "DomainMetadataType"
}

func (t DomainMetadataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cfSslStatusAttribute, ok := attributes["cf_ssl_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cf_ssl_status is missing from object`)

		return nil, diags
	}

	cfSslStatusVal, ok := cfSslStatusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cf_ssl_status expected to be basetypes.StringValue, was: %T`, cfSslStatusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DomainMetadataValue{
		CfSslStatus: cfSslStatusVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewDomainMetadataValueNull() DomainMetadataValue {
	return DomainMetadataValue{
		state: attr.ValueStateNull,
	}
}

func NewDomainMetadataValueUnknown() DomainMetadataValue {
	return DomainMetadataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDomainMetadataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DomainMetadataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DomainMetadataValue Attribute Value",
				"While creating a DomainMetadataValue value, a missing attribute value was detected. "+
					"A DomainMetadataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DomainMetadataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DomainMetadataValue Attribute Type",
				"While creating a DomainMetadataValue value, an invalid attribute value was detected. "+
					"A DomainMetadataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DomainMetadataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DomainMetadataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DomainMetadataValue Attribute Value",
				"While creating a DomainMetadataValue value, an extra attribute value was detected. "+
					"A DomainMetadataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DomainMetadataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDomainMetadataValueUnknown(), diags
	}

	cfSslStatusAttribute, ok := attributes["cf_ssl_status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cf_ssl_status is missing from object`)

		return NewDomainMetadataValueUnknown(), diags
	}

	cfSslStatusVal, ok := cfSslStatusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cf_ssl_status expected to be basetypes.StringValue, was: %T`, cfSslStatusAttribute))
	}

	if diags.HasError() {
		return NewDomainMetadataValueUnknown(), diags
	}

	return DomainMetadataValue{
		CfSslStatus: cfSslStatusVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewDomainMetadataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DomainMetadataValue {
	object, diags := NewDomainMetadataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDomainMetadataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DomainMetadataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDomainMetadataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDomainMetadataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDomainMetadataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDomainMetadataValueMust(DomainMetadataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DomainMetadataType) ValueType(ctx context.Context) attr.Value {
	return DomainMetadataValue{}
}

var _ basetypes.ObjectValuable = DomainMetadataValue{}

type DomainMetadataValue struct {
	CfSslStatus basetypes.StringValue `tfsdk:"cf_ssl_status"`
	state       attr.ValueState
}

func (v DomainMetadataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["cf_ssl_status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.CfSslStatus.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cf_ssl_status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DomainMetadataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DomainMetadataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DomainMetadataValue) String() string {
	return "DomainMetadataValue"
}

func (v DomainMetadataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"cf_ssl_status": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cf_ssl_status": v.CfSslStatus,
		})

	return objVal, diags
}

func (v DomainMetadataValue) Equal(o attr.Value) bool {
	other, ok := o.(DomainMetadataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CfSslStatus.Equal(other.CfSslStatus) {
		return false
	}

	return true
}

func (v DomainMetadataValue) Type(ctx context.Context) attr.Type {
	return DomainMetadataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DomainMetadataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cf_ssl_status": basetypes.StringType{},
	}
}
