// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_surface

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SurfaceDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"anonymous_user_tracking": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether anonymous-user telemetry is collected.",
				MarkdownDescription: "Whether anonymous-user telemetry is collected.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique surface identifier.",
				MarkdownDescription: "Unique surface identifier.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of the surface.",
				MarkdownDescription: "Display name of the surface.",
			},
			"slug": schema.StringAttribute{
				Computed:            true,
				Description:         "Surface URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Surface URL slug, using lowercase letters, numbers, and hyphens.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "Application framework used by the surface.",
				MarkdownDescription: "Application framework used by the surface.",
			},
			"workspace_slug": schema.StringAttribute{
				Required:            true,
				Description:         "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type SurfaceModel struct {
	AnonymousUserTracking types.Bool   `tfsdk:"anonymous_user_tracking"`
	Id                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	Slug                  types.String `tfsdk:"slug"`
	Type                  types.String `tfsdk:"type"`
	WorkspaceSlug         types.String `tfsdk:"workspace_slug"`
}
