// Code generated by Fern. DO NOT EDIT.

package private

import (
    context "context"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    keys "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/keys"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Creates a private API key with explicit scopes and expiration. Supply surfaceSlug for a surface key; omit it for a workspace key. Grants cannot exceed the caller's permissions. Reuse the same idempotency key and request after an uncertain response.
// 
// Example:
// 
// 	request := &keys.CreatePrivateRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    IdempotencyKey: "idempotencyKey",
// 	    Name: "name",
// 	    Scopes: []keys.CreatePrivateRequestScopesItem{
// 	        keys.CreatePrivateRequestScopesItemOrgSurfacesRead,
// 	    },
// 	}
// 	client.Keys.Private.Create(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) Create(
    ctx context.Context,
    request *keys.CreatePrivateRequest,
    opts ...option.RequestOption,
) (*sdk.CreateWorkspaceAPIKeyResponse, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Reads a workspace or surface key's grants and expiration without retrieving its secret. Requires workspace authentication read permission for workspace keys or surface read permission for surface keys.
// 
// Example:
// 
// 	request := &keys.GetPrivateRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    APIKeyID: "apiKeyId",
// 	}
// 	client.Keys.Private.Get(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) Get(
    ctx context.Context,
    request *keys.GetPrivateRequest,
    opts ...option.RequestOption,
) (*sdk.ReadPrivateKeyResponse, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Revokes a workspace or surface API key so it can no longer authorize API requests. Requires workspace authentication write permission for workspace keys or surface write permission for surface keys.
// 
// Example:
// 
// 	request := &keys.DeletePrivateRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    APIKeyID: "apiKeyId",
// 	}
// 	client.Keys.Private.Delete(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) Delete(
    ctx context.Context,
    request *keys.DeletePrivateRequest,
    opts ...option.RequestOption,
) (*sdk.RevokeWorkspaceAPIKeyResponse, error){
    response, err := c.WithRawResponse.Delete(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

