// Code generated by Fern. DO NOT EDIT.

package private

import (
    context "context"
    http "net/http"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    keys "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/keys"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) Create(
    ctx context.Context,
    request *keys.CreatePrivateRequest,
    opts ...option.RequestOption,
) (*core.Response[*sdk.CreateWorkspaceAPIKeyResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v3/workspaces/%v/api-keys",
        request.WorkspaceSlug,
    )
    authHeaders, authErr := r.options.AuthHeadersForEndpoint([][]string{{"clerkSession"}})
    if authErr != nil {
        return nil, authErr
    }
    headers := internal.MergeHeaders(
        internal.MergeHeaders(
            r.options.ToHeader(),
            options.ToHeader(),
        ),
        authHeaders,
    )
    headers.Add("Content-Type", "application/json")
    var response *sdk.CreateWorkspaceAPIKeyResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(keys.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*sdk.CreateWorkspaceAPIKeyResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Get(
    ctx context.Context,
    request *keys.GetPrivateRequest,
    opts ...option.RequestOption,
) (*core.Response[*sdk.ReadPrivateKeyResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v3/workspaces/%v/api-keys/%v",
        request.WorkspaceSlug,
        request.APIKeyID,
    )
    authHeaders, authErr := r.options.AuthHeadersForEndpoint([][]string{{"clerkSession"}})
    if authErr != nil {
        return nil, authErr
    }
    headers := internal.MergeHeaders(
        internal.MergeHeaders(
            r.options.ToHeader(),
            options.ToHeader(),
        ),
        authHeaders,
    )
    var response *sdk.ReadPrivateKeyResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(keys.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*sdk.ReadPrivateKeyResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Delete(
    ctx context.Context,
    request *keys.DeletePrivateRequest,
    opts ...option.RequestOption,
) (*core.Response[*sdk.RevokeWorkspaceAPIKeyResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v3/workspaces/%v/api-keys/%v",
        request.WorkspaceSlug,
        request.APIKeyID,
    )
    authHeaders, authErr := r.options.AuthHeadersForEndpoint([][]string{{"clerkSession"}})
    if authErr != nil {
        return nil, authErr
    }
    headers := internal.MergeHeaders(
        internal.MergeHeaders(
            r.options.ToHeader(),
            options.ToHeader(),
        ),
        authHeaders,
    )
    var response *sdk.RevokeWorkspaceAPIKeyResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodDelete,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(keys.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*sdk.RevokeWorkspaceAPIKeyResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

