// Code generated by Fern. DO NOT EDIT.

package domains_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    client "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/client"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func VerifyAuthHeaders(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    headerMatchers map[string]string,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}`)
    for name, matcher := range headerMatchers {
        reqBody.WriteString(`,"`)
        reqBody.WriteString(name)
        reqBody.WriteString(`":`)
        reqBody.WriteString(matcher)
    }
    reqBody.WriteString(`}}`)
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, 1, len(result.Requests), "expected exactly one request with the routed auth headers for "+testId)
}

func TestDomainsByIDIncludeDeletedWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.ByIDIncludeDeletedDomainsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.ByIDIncludeDeletedDomainsRequestArgs{
                DomainID: "domainId",
            },
        }
    _, invocationErr :=     client.Domains.ByIDIncludeDeleted(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestDomainsByIDIncludeDeletedWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestDomainsByIDIncludeDeletedWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/domains.byIdIncludeDeleted", nil, 1)
    VerifyAuthHeaders(t, "TestDomainsByIDIncludeDeletedWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/domains.byIdIncludeDeleted", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}


