// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_integration

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func IntegrationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"integration": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Unique integration installation identifier.",
							MarkdownDescription: "Unique integration installation identifier.",
						},
						"provider": schema.StringAttribute{
							Computed:            true,
							Description:         "Installed integration provider.",
							MarkdownDescription: "Installed integration provider.",
						},
						"status": schema.StringAttribute{
							Computed:            true,
							Description:         "Current integration installation status.",
							MarkdownDescription: "Current integration installation status.",
						},
					},
					CustomType: IntegrationType{
						ObjectType: types.ObjectType{
							AttrTypes: IntegrationValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"workspace_slug": schema.StringAttribute{
				Required:            true,
				Description:         "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type IntegrationModel struct {
	Integration   types.Set    `tfsdk:"integration"`
	WorkspaceSlug types.String `tfsdk:"workspace_slug"`
}

var _ basetypes.ObjectTypable = IntegrationType{}

type IntegrationType struct {
	basetypes.ObjectType
}

func (t IntegrationType) Equal(o attr.Type) bool {
	other, ok := o.(IntegrationType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IntegrationType) String() string {
	return "IntegrationType"
}

func (t IntegrationType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	providerAttribute, ok := attributes["provider"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider is missing from object`)

		return nil, diags
	}

	providerVal, ok := providerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider expected to be basetypes.StringValue, was: %T`, providerAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IntegrationValue{
		Id:       idVal,
		Provider: providerVal,
		Status:   statusVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewIntegrationValueNull() IntegrationValue {
	return IntegrationValue{
		state: attr.ValueStateNull,
	}
}

func NewIntegrationValueUnknown() IntegrationValue {
	return IntegrationValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIntegrationValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IntegrationValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IntegrationValue Attribute Value",
				"While creating a IntegrationValue value, a missing attribute value was detected. "+
					"A IntegrationValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IntegrationValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IntegrationValue Attribute Type",
				"While creating a IntegrationValue value, an invalid attribute value was detected. "+
					"A IntegrationValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IntegrationValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IntegrationValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IntegrationValue Attribute Value",
				"While creating a IntegrationValue value, an extra attribute value was detected. "+
					"A IntegrationValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IntegrationValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIntegrationValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewIntegrationValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	providerAttribute, ok := attributes["provider"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider is missing from object`)

		return NewIntegrationValueUnknown(), diags
	}

	providerVal, ok := providerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider expected to be basetypes.StringValue, was: %T`, providerAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewIntegrationValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewIntegrationValueUnknown(), diags
	}

	return IntegrationValue{
		Id:       idVal,
		Provider: providerVal,
		Status:   statusVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewIntegrationValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IntegrationValue {
	object, diags := NewIntegrationValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIntegrationValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IntegrationType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIntegrationValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIntegrationValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIntegrationValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIntegrationValueMust(IntegrationValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IntegrationType) ValueType(ctx context.Context) attr.Value {
	return IntegrationValue{}
}

var _ basetypes.ObjectValuable = IntegrationValue{}

type IntegrationValue struct {
	Id       basetypes.StringValue `tfsdk:"id"`
	Provider basetypes.StringValue `tfsdk:"provider"`
	Status   basetypes.StringValue `tfsdk:"status"`
	state    attr.ValueState
}

func (v IntegrationValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["provider"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Provider.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["provider"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IntegrationValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IntegrationValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IntegrationValue) String() string {
	return "IntegrationValue"
}

func (v IntegrationValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":       basetypes.StringType{},
		"provider": basetypes.StringType{},
		"status":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":       v.Id,
			"provider": v.Provider,
			"status":   v.Status,
		})

	return objVal, diags
}

func (v IntegrationValue) Equal(o attr.Value) bool {
	other, ok := o.(IntegrationValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Provider.Equal(other.Provider) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v IntegrationValue) Type(ctx context.Context) attr.Type {
	return IntegrationType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IntegrationValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":       basetypes.StringType{},
		"provider": basetypes.StringType{},
		"status":   basetypes.StringType{},
	}
}
