// Code generated by Fern. DO NOT EDIT.

package client

import (
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    private "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/keys/private"
    public "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/keys/public"
)


type Client struct {
    Private *private.Client
    Public *public.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        Private: private.NewClient(options),
        Public: public.NewClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

