// Code generated by Fern. DO NOT EDIT.

package domains

import (
    context "context"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Read a tracking domain by ID, including its deletion marker. Requires workspace domain read permission; null can also indicate insufficient access. Pass the workspace slug in the URL and operation arguments inside the JSON body as { args: ... }. Inspect the request schema for required fields and exact identifier formats. This operation is read-only despite using POST. Permission-filtered queries may return an empty result; do not assume that proves the resource does not exist. Only use pagination arguments declared in the schema.
// 
// Example:
// 
// 	request := &sdk.ByIDIncludeDeletedDomainsRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    Args: &sdk.ByIDIncludeDeletedDomainsRequestArgs{
// 	        DomainID: "domainId",
// 	    },
// 	}
// 	client.Domains.ByIDIncludeDeleted(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) ByIDIncludeDeleted(
    ctx context.Context,
    request *sdk.ByIDIncludeDeletedDomainsRequest,
    opts ...option.RequestOption,
) (*sdk.QueryDomainsByIDIncludeDeletedResponse, error){
    response, err := c.WithRawResponse.ByIDIncludeDeleted(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

