// Code generated by Fern. DO NOT EDIT.

package domains

import (
    context "context"
    http "net/http"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) ByIDIncludeDeleted(
    ctx context.Context,
    request *sdk.ByIDIncludeDeletedDomainsRequest,
    opts ...option.RequestOption,
) (*core.Response[*sdk.QueryDomainsByIDIncludeDeletedResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        r.baseURL,
        "",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/v3/workspaces/%v/queries/domains.byIdIncludeDeleted",
        request.WorkspaceSlug,
    )
    authHeaders, authErr := r.options.AuthHeadersForEndpoint([][]string{{"clerkSession"}})
    if authErr != nil {
        return nil, authErr
    }
    headers := internal.MergeHeaders(
        internal.MergeHeaders(
            r.options.ToHeader(),
            options.ToHeader(),
        ),
        authHeaders,
    )
    headers.Add("Content-Type", "application/json")
    var response *sdk.QueryDomainsByIDIncludeDeletedResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ResponseIsOptional: true,
            ErrorDecoder: internal.NewErrorDecoder(sdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*sdk.QueryDomainsByIDIncludeDeletedResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

