// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_surface_repository

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SurfaceRepositoryResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"args": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"integration_id": schema.StringAttribute{
						Required:            true,
						Description:         "Identifier of the existing integration installation.",
						MarkdownDescription: "Identifier of the existing integration installation.",
					},
					"repository_id": schema.StringAttribute{
						Required:            true,
						Description:         "Repository identifier exposed by the integration.",
						MarkdownDescription: "Repository identifier exposed by the integration.",
					},
					"surface_slug": schema.StringAttribute{
						Required:            true,
						Description:         "Surface URL slug, using lowercase letters, numbers, and hyphens.",
						MarkdownDescription: "Surface URL slug, using lowercase letters, numbers, and hyphens.",
						Validators: []validator.String{
							stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
						},
					},
					"working_directory": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Repository-relative working directory. Omit for the repository root.",
						MarkdownDescription: "Repository-relative working directory. Omit for the repository root.",
					},
				},
				CustomType: ArgsType{
					ObjectType: types.ObjectType{
						AttrTypes: ArgsValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique surface identifier.",
				MarkdownDescription: "Unique surface identifier.",
			},
			"workspace_slug": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				MarkdownDescription: "Workspace URL slug, using lowercase letters, numbers, and hyphens.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type SurfaceRepositoryModel struct {
	Args          ArgsValue    `tfsdk:"args"`
	Id            types.String `tfsdk:"id"`
	WorkspaceSlug types.String `tfsdk:"workspace_slug"`
}

var _ basetypes.ObjectTypable = ArgsType{}

type ArgsType struct {
	basetypes.ObjectType
}

func (t ArgsType) Equal(o attr.Type) bool {
	other, ok := o.(ArgsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ArgsType) String() string {
	return "ArgsType"
}

func (t ArgsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	integrationIdAttribute, ok := attributes["integration_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`integration_id is missing from object`)

		return nil, diags
	}

	integrationIdVal, ok := integrationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`integration_id expected to be basetypes.StringValue, was: %T`, integrationIdAttribute))
	}

	repositoryIdAttribute, ok := attributes["repository_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`repository_id is missing from object`)

		return nil, diags
	}

	repositoryIdVal, ok := repositoryIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`repository_id expected to be basetypes.StringValue, was: %T`, repositoryIdAttribute))
	}

	surfaceSlugAttribute, ok := attributes["surface_slug"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`surface_slug is missing from object`)

		return nil, diags
	}

	surfaceSlugVal, ok := surfaceSlugAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`surface_slug expected to be basetypes.StringValue, was: %T`, surfaceSlugAttribute))
	}

	workingDirectoryAttribute, ok := attributes["working_directory"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`working_directory is missing from object`)

		return nil, diags
	}

	workingDirectoryVal, ok := workingDirectoryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`working_directory expected to be basetypes.StringValue, was: %T`, workingDirectoryAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ArgsValue{
		IntegrationId:    integrationIdVal,
		RepositoryId:     repositoryIdVal,
		SurfaceSlug:      surfaceSlugVal,
		WorkingDirectory: workingDirectoryVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewArgsValueNull() ArgsValue {
	return ArgsValue{
		state: attr.ValueStateNull,
	}
}

func NewArgsValueUnknown() ArgsValue {
	return ArgsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewArgsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ArgsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ArgsValue Attribute Value",
				"While creating a ArgsValue value, a missing attribute value was detected. "+
					"A ArgsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ArgsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ArgsValue Attribute Type",
				"While creating a ArgsValue value, an invalid attribute value was detected. "+
					"A ArgsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ArgsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ArgsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ArgsValue Attribute Value",
				"While creating a ArgsValue value, an extra attribute value was detected. "+
					"A ArgsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ArgsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewArgsValueUnknown(), diags
	}

	integrationIdAttribute, ok := attributes["integration_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`integration_id is missing from object`)

		return NewArgsValueUnknown(), diags
	}

	integrationIdVal, ok := integrationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`integration_id expected to be basetypes.StringValue, was: %T`, integrationIdAttribute))
	}

	repositoryIdAttribute, ok := attributes["repository_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`repository_id is missing from object`)

		return NewArgsValueUnknown(), diags
	}

	repositoryIdVal, ok := repositoryIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`repository_id expected to be basetypes.StringValue, was: %T`, repositoryIdAttribute))
	}

	surfaceSlugAttribute, ok := attributes["surface_slug"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`surface_slug is missing from object`)

		return NewArgsValueUnknown(), diags
	}

	surfaceSlugVal, ok := surfaceSlugAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`surface_slug expected to be basetypes.StringValue, was: %T`, surfaceSlugAttribute))
	}

	workingDirectoryAttribute, ok := attributes["working_directory"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`working_directory is missing from object`)

		return NewArgsValueUnknown(), diags
	}

	workingDirectoryVal, ok := workingDirectoryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`working_directory expected to be basetypes.StringValue, was: %T`, workingDirectoryAttribute))
	}

	if diags.HasError() {
		return NewArgsValueUnknown(), diags
	}

	return ArgsValue{
		IntegrationId:    integrationIdVal,
		RepositoryId:     repositoryIdVal,
		SurfaceSlug:      surfaceSlugVal,
		WorkingDirectory: workingDirectoryVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewArgsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ArgsValue {
	object, diags := NewArgsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewArgsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ArgsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewArgsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewArgsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewArgsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewArgsValueMust(ArgsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ArgsType) ValueType(ctx context.Context) attr.Value {
	return ArgsValue{}
}

var _ basetypes.ObjectValuable = ArgsValue{}

type ArgsValue struct {
	IntegrationId    basetypes.StringValue `tfsdk:"integration_id"`
	RepositoryId     basetypes.StringValue `tfsdk:"repository_id"`
	SurfaceSlug      basetypes.StringValue `tfsdk:"surface_slug"`
	WorkingDirectory basetypes.StringValue `tfsdk:"working_directory"`
	state            attr.ValueState
}

func (v ArgsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["integration_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["repository_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["surface_slug"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["working_directory"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.IntegrationId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["integration_id"] = val

		val, err = v.RepositoryId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["repository_id"] = val

		val, err = v.SurfaceSlug.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["surface_slug"] = val

		val, err = v.WorkingDirectory.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["working_directory"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ArgsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ArgsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ArgsValue) String() string {
	return "ArgsValue"
}

func (v ArgsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"integration_id":    basetypes.StringType{},
		"repository_id":     basetypes.StringType{},
		"surface_slug":      basetypes.StringType{},
		"working_directory": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"integration_id":    v.IntegrationId,
			"repository_id":     v.RepositoryId,
			"surface_slug":      v.SurfaceSlug,
			"working_directory": v.WorkingDirectory,
		})

	return objVal, diags
}

func (v ArgsValue) Equal(o attr.Value) bool {
	other, ok := o.(ArgsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IntegrationId.Equal(other.IntegrationId) {
		return false
	}

	if !v.RepositoryId.Equal(other.RepositoryId) {
		return false
	}

	if !v.SurfaceSlug.Equal(other.SurfaceSlug) {
		return false
	}

	if !v.WorkingDirectory.Equal(other.WorkingDirectory) {
		return false
	}

	return true
}

func (v ArgsValue) Type(ctx context.Context) attr.Type {
	return ArgsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ArgsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"integration_id":    basetypes.StringType{},
		"repository_id":     basetypes.StringType{},
		"surface_slug":      basetypes.StringType{},
		"working_directory": basetypes.StringType{},
	}
}
