// Code generated by Fern. DO NOT EDIT.

package client

import (
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    client "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/keys/client"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
    surfaces "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/surfaces"
    workspaces "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/workspaces"
)


type Client struct {
    Workspaces *workspaces.Client
    Surfaces *surfaces.Client
    Keys *client.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
    options := core.NewRequestOptions(opts...)
    return &Client{
        Workspaces: workspaces.NewClient(options),
        Surfaces: surfaces.NewClient(options),
        Keys: client.NewClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

