// Code generated by Fern. DO NOT EDIT.

package integrations_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    client "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/client"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func VerifyAuthHeaders(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    headerMatchers map[string]string,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}`)
    for name, matcher := range headerMatchers {
        reqBody.WriteString(`,"`)
        reqBody.WriteString(name)
        reqBody.WriteString(`":`)
        reqBody.WriteString(matcher)
    }
    reqBody.WriteString(`}}`)
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, 1, len(result.Requests), "expected exactly one request with the routed auth headers for "+testId)
}

func TestIntegrationsInstallationsWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.InstallationsIntegrationsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.InstallationsIntegrationsRequestArgs{
                Providers: []sdk.InstallationsIntegrationsRequestArgsProvidersItem{
                    sdk.InstallationsIntegrationsRequestArgsProvidersItemGithub,
                },
            },
        }
    _, invocationErr :=     client.Integrations.Installations(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestIntegrationsInstallationsWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestIntegrationsInstallationsWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/integrations.installations", nil, 1)
    VerifyAuthHeaders(t, "TestIntegrationsInstallationsWithWireMock", "POST", "/v3/workspaces/workspaceSlug/queries/integrations.installations", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestIntegrationsLinkSurfaceToDestinationWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.LinkSurfaceToDestinationIntegrationsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.LinkSurfaceToDestinationIntegrationsRequestArgs{
                IntegrationID: "integrationId",
                ProjectID: "projectId",
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Integrations.LinkSurfaceToDestination(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestIntegrationsLinkSurfaceToDestinationWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestIntegrationsLinkSurfaceToDestinationWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.linkSurfaceToDestination", nil, 1)
    VerifyAuthHeaders(t, "TestIntegrationsLinkSurfaceToDestinationWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.linkSurfaceToDestination", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestIntegrationsLinkSurfaceToRepositoryWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.LinkSurfaceToRepositoryIntegrationsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.LinkSurfaceToRepositoryIntegrationsRequestArgs{
                IntegrationID: "integrationId",
                RepositoryID: "repositoryId",
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Integrations.LinkSurfaceToRepository(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestIntegrationsLinkSurfaceToRepositoryWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestIntegrationsLinkSurfaceToRepositoryWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.linkSurfaceToRepository", nil, 1)
    VerifyAuthHeaders(t, "TestIntegrationsLinkSurfaceToRepositoryWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.linkSurfaceToRepository", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestIntegrationsUnlinkSurfaceDestinationMappingWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.UnlinkSurfaceDestinationMappingIntegrationsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.UnlinkSurfaceDestinationMappingIntegrationsRequestArgs{
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Integrations.UnlinkSurfaceDestinationMapping(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestIntegrationsUnlinkSurfaceDestinationMappingWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestIntegrationsUnlinkSurfaceDestinationMappingWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.unlinkSurfaceDestinationMapping", nil, 1)
    VerifyAuthHeaders(t, "TestIntegrationsUnlinkSurfaceDestinationMappingWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.unlinkSurfaceDestinationMapping", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}

func TestIntegrationsUnlinkSurfaceMappingWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithToken("test-token"),
    )
        request := &sdk.UnlinkSurfaceMappingIntegrationsRequest{
            WorkspaceSlug: "workspaceSlug",
            Args: &sdk.UnlinkSurfaceMappingIntegrationsRequestArgs{
                SurfaceSlug: "surfaceSlug",
            },
        }
    _, invocationErr :=     client.Integrations.UnlinkSurfaceMapping(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestIntegrationsUnlinkSurfaceMappingWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestIntegrationsUnlinkSurfaceMappingWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.unlinkSurfaceMapping", nil, 1)
    VerifyAuthHeaders(t, "TestIntegrationsUnlinkSurfaceMappingWithWireMock", "POST", "/v3/workspaces/workspaceSlug/actions/integrations.unlinkSurfaceMapping", map[string]string{
    		"Authorization": `{"matches":"Bearer .*"}`,
    	})
}


