// Code generated by Fern. DO NOT EDIT.

package keys

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreatePrivateRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug", func(t *testing.T) {
		obj := &CreatePrivateRequest{}
		var fernTestValueWorkspaceSlug string
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)
		assert.Equal(t, fernTestValueWorkspaceSlug, obj.WorkspaceSlug)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSurfaceSlug", func(t *testing.T) {
		obj := &CreatePrivateRequest{}
		var fernTestValueSurfaceSlug *string
		obj.SetSurfaceSlug(fernTestValueSurfaceSlug)
		assert.Equal(t, fernTestValueSurfaceSlug, obj.SurfaceSlug)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &CreatePrivateRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &CreatePrivateRequest{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetScopes", func(t *testing.T) {
		obj := &CreatePrivateRequest{}
		var fernTestValueScopes []CreatePrivateRequestScopesItem
		obj.SetScopes(fernTestValueScopes)
		assert.Equal(t, fernTestValueScopes, obj.Scopes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSecondsUntilExpiration", func(t *testing.T) {
		obj := &CreatePrivateRequest{}
		var fernTestValueSecondsUntilExpiration *int
		obj.SetSecondsUntilExpiration(fernTestValueSecondsUntilExpiration)
		assert.Equal(t, fernTestValueSecondsUntilExpiration, obj.SecondsUntilExpiration)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreatePrivateRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePrivateRequest{}
		var fernTestValueWorkspaceSlug string

		// Act
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSurfaceSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePrivateRequest{}
		var fernTestValueSurfaceSlug *string

		// Act
		obj.SetSurfaceSlug(fernTestValueSurfaceSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePrivateRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePrivateRequest{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetScopes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePrivateRequest{}
		var fernTestValueScopes []CreatePrivateRequestScopesItem

		// Act
		obj.SetScopes(fernTestValueScopes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSecondsUntilExpiration_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreatePrivateRequest{}
		var fernTestValueSecondsUntilExpiration *int

		// Act
		obj.SetSecondsUntilExpiration(fernTestValueSecondsUntilExpiration)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeletePrivateRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug", func(t *testing.T) {
		obj := &DeletePrivateRequest{}
		var fernTestValueWorkspaceSlug string
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)
		assert.Equal(t, fernTestValueWorkspaceSlug, obj.WorkspaceSlug)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAPIKeyID", func(t *testing.T) {
		obj := &DeletePrivateRequest{}
		var fernTestValueAPIKeyID string
		obj.SetAPIKeyID(fernTestValueAPIKeyID)
		assert.Equal(t, fernTestValueAPIKeyID, obj.APIKeyID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeletePrivateRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeletePrivateRequest{}
		var fernTestValueWorkspaceSlug string

		// Act
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAPIKeyID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeletePrivateRequest{}
		var fernTestValueAPIKeyID string

		// Act
		obj.SetAPIKeyID(fernTestValueAPIKeyID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetPrivateRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug", func(t *testing.T) {
		obj := &GetPrivateRequest{}
		var fernTestValueWorkspaceSlug string
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)
		assert.Equal(t, fernTestValueWorkspaceSlug, obj.WorkspaceSlug)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAPIKeyID", func(t *testing.T) {
		obj := &GetPrivateRequest{}
		var fernTestValueAPIKeyID string
		obj.SetAPIKeyID(fernTestValueAPIKeyID)
		assert.Equal(t, fernTestValueAPIKeyID, obj.APIKeyID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetPrivateRequest(t *testing.T) {
	t.Run("SetWorkspaceSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPrivateRequest{}
		var fernTestValueWorkspaceSlug string

		// Act
		obj.SetWorkspaceSlug(fernTestValueWorkspaceSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAPIKeyID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPrivateRequest{}
		var fernTestValueAPIKeyID string

		// Act
		obj.SetAPIKeyID(fernTestValueAPIKeyID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumCreatePrivateRequestScopesItem(t *testing.T) {
	t.Run("NewFromString_org_surfaces_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:surfaces:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:surfaces:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_surfaces_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:surfaces:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:surfaces:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_surfaces_delete", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:surfaces:delete")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:surfaces:delete"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_problems_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:problems:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:problems:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_problems_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:problems:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:problems:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_support_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:support:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:support:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_support_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:support:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:support:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_replays_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:replays:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:replays:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_source_context_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:source_context:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:source_context:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_integration_settings_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:integration_settings:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:integration_settings:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_integration_settings_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:integration_settings:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:integration_settings:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_members_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_members:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_members:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_members_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_members:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_members:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_billing_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_billing:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_billing:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_billing_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_billing:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_billing:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_basics_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_basics:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_basics:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_basics_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_basics:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_basics:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_domains_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_domains:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_domains:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_domains_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_domains:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_domains:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_auth_read", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_auth:read")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_auth:read"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_auth_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace_auth:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace_auth:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_destroy", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace:destroy")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace:destroy"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_org_workspace_transfer_ownership", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("org:workspace:transfer_ownership")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("org:workspace:transfer_ownership"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_release_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("release:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("release:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ingest_write", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreatePrivateRequestScopesItemFromString("ingest:write")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreatePrivateRequestScopesItem("ingest:write"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreatePrivateRequestScopesItemFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreatePrivateRequestScopesItemFromString("org:surfaces:read")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
