// Code generated by Fern. DO NOT EDIT.

package keys

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	createPrivateRequestFieldWorkspaceSlug          = big.NewInt(1 << 0)
	createPrivateRequestFieldSurfaceSlug            = big.NewInt(1 << 1)
	createPrivateRequestFieldIdempotencyKey         = big.NewInt(1 << 2)
	createPrivateRequestFieldName                   = big.NewInt(1 << 3)
	createPrivateRequestFieldScopes                 = big.NewInt(1 << 4)
	createPrivateRequestFieldSecondsUntilExpiration = big.NewInt(1 << 5)
)

type CreatePrivateRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string `json:"-" url:"-"`
	// Surface URL slug, using lowercase letters, numbers, and hyphens.
	SurfaceSlug    *string `json:"surfaceSlug,omitempty" url:"-"`
	IdempotencyKey string  `json:"idempotencyKey" url:"-"`
	// Display name of the key.
	Name string `json:"name" url:"-"`
	// Permission scopes granted to the key.
	Scopes []CreatePrivateRequestScopesItem `json:"scopes" url:"-"`
	// Positive lifetime in seconds, or null for no expiry.
	SecondsUntilExpiration *int `json:"secondsUntilExpiration,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePrivateRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePrivateRequest) SetWorkspaceSlug(workspaceSlug string) {
	c.WorkspaceSlug = workspaceSlug
	c.require(createPrivateRequestFieldWorkspaceSlug)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePrivateRequest) SetSurfaceSlug(surfaceSlug *string) {
	c.SurfaceSlug = surfaceSlug
	c.require(createPrivateRequestFieldSurfaceSlug)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePrivateRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createPrivateRequestFieldIdempotencyKey)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePrivateRequest) SetName(name string) {
	c.Name = name
	c.require(createPrivateRequestFieldName)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePrivateRequest) SetScopes(scopes []CreatePrivateRequestScopesItem) {
	c.Scopes = scopes
	c.require(createPrivateRequestFieldScopes)
}

// SetSecondsUntilExpiration sets the SecondsUntilExpiration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePrivateRequest) SetSecondsUntilExpiration(secondsUntilExpiration *int) {
	c.SecondsUntilExpiration = secondsUntilExpiration
	c.require(createPrivateRequestFieldSecondsUntilExpiration)
}

func (c *CreatePrivateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePrivateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePrivateRequest(body)
	return nil
}

func (c *CreatePrivateRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePrivateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deletePrivateRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	deletePrivateRequestFieldAPIKeyID      = big.NewInt(1 << 1)
)

type DeletePrivateRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string `json:"-" url:"-"`
	APIKeyID      string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePrivateRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateRequest) SetWorkspaceSlug(workspaceSlug string) {
	d.WorkspaceSlug = workspaceSlug
	d.require(deletePrivateRequestFieldWorkspaceSlug)
}

// SetAPIKeyID sets the APIKeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateRequest) SetAPIKeyID(apiKeyID string) {
	d.APIKeyID = apiKeyID
	d.require(deletePrivateRequestFieldAPIKeyID)
}

var (
	getPrivateRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	getPrivateRequestFieldAPIKeyID      = big.NewInt(1 << 1)
)

type GetPrivateRequest struct {
	// Workspace URL slug, using lowercase letters, numbers, and hyphens.
	WorkspaceSlug string `json:"-" url:"-"`
	APIKeyID      string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPrivateRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateRequest) SetWorkspaceSlug(workspaceSlug string) {
	g.WorkspaceSlug = workspaceSlug
	g.require(getPrivateRequestFieldWorkspaceSlug)
}

// SetAPIKeyID sets the APIKeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateRequest) SetAPIKeyID(apiKeyID string) {
	g.APIKeyID = apiKeyID
	g.require(getPrivateRequestFieldAPIKeyID)
}

type CreatePrivateRequestScopesItem string

const (
	CreatePrivateRequestScopesItemOrgSurfacesRead               CreatePrivateRequestScopesItem = "org:surfaces:read"
	CreatePrivateRequestScopesItemOrgSurfacesWrite              CreatePrivateRequestScopesItem = "org:surfaces:write"
	CreatePrivateRequestScopesItemOrgSurfacesDelete             CreatePrivateRequestScopesItem = "org:surfaces:delete"
	CreatePrivateRequestScopesItemOrgProblemsRead               CreatePrivateRequestScopesItem = "org:problems:read"
	CreatePrivateRequestScopesItemOrgProblemsWrite              CreatePrivateRequestScopesItem = "org:problems:write"
	CreatePrivateRequestScopesItemOrgSupportRead                CreatePrivateRequestScopesItem = "org:support:read"
	CreatePrivateRequestScopesItemOrgSupportWrite               CreatePrivateRequestScopesItem = "org:support:write"
	CreatePrivateRequestScopesItemOrgReplaysRead                CreatePrivateRequestScopesItem = "org:replays:read"
	CreatePrivateRequestScopesItemOrgSourceContextRead          CreatePrivateRequestScopesItem = "org:source_context:read"
	CreatePrivateRequestScopesItemOrgIntegrationSettingsRead    CreatePrivateRequestScopesItem = "org:integration_settings:read"
	CreatePrivateRequestScopesItemOrgIntegrationSettingsWrite   CreatePrivateRequestScopesItem = "org:integration_settings:write"
	CreatePrivateRequestScopesItemOrgWorkspaceMembersRead       CreatePrivateRequestScopesItem = "org:workspace_members:read"
	CreatePrivateRequestScopesItemOrgWorkspaceMembersWrite      CreatePrivateRequestScopesItem = "org:workspace_members:write"
	CreatePrivateRequestScopesItemOrgWorkspaceBillingRead       CreatePrivateRequestScopesItem = "org:workspace_billing:read"
	CreatePrivateRequestScopesItemOrgWorkspaceBillingWrite      CreatePrivateRequestScopesItem = "org:workspace_billing:write"
	CreatePrivateRequestScopesItemOrgWorkspaceBasicsRead        CreatePrivateRequestScopesItem = "org:workspace_basics:read"
	CreatePrivateRequestScopesItemOrgWorkspaceBasicsWrite       CreatePrivateRequestScopesItem = "org:workspace_basics:write"
	CreatePrivateRequestScopesItemOrgWorkspaceDomainsRead       CreatePrivateRequestScopesItem = "org:workspace_domains:read"
	CreatePrivateRequestScopesItemOrgWorkspaceDomainsWrite      CreatePrivateRequestScopesItem = "org:workspace_domains:write"
	CreatePrivateRequestScopesItemOrgWorkspaceAuthRead          CreatePrivateRequestScopesItem = "org:workspace_auth:read"
	CreatePrivateRequestScopesItemOrgWorkspaceAuthWrite         CreatePrivateRequestScopesItem = "org:workspace_auth:write"
	CreatePrivateRequestScopesItemOrgWorkspaceDestroy           CreatePrivateRequestScopesItem = "org:workspace:destroy"
	CreatePrivateRequestScopesItemOrgWorkspaceTransferOwnership CreatePrivateRequestScopesItem = "org:workspace:transfer_ownership"
	CreatePrivateRequestScopesItemReleaseWrite                  CreatePrivateRequestScopesItem = "release:write"
	CreatePrivateRequestScopesItemIngestWrite                   CreatePrivateRequestScopesItem = "ingest:write"
)

func NewCreatePrivateRequestScopesItemFromString(s string) (CreatePrivateRequestScopesItem, error) {
	switch s {
	case "org:surfaces:read":
		return CreatePrivateRequestScopesItemOrgSurfacesRead, nil
	case "org:surfaces:write":
		return CreatePrivateRequestScopesItemOrgSurfacesWrite, nil
	case "org:surfaces:delete":
		return CreatePrivateRequestScopesItemOrgSurfacesDelete, nil
	case "org:problems:read":
		return CreatePrivateRequestScopesItemOrgProblemsRead, nil
	case "org:problems:write":
		return CreatePrivateRequestScopesItemOrgProblemsWrite, nil
	case "org:support:read":
		return CreatePrivateRequestScopesItemOrgSupportRead, nil
	case "org:support:write":
		return CreatePrivateRequestScopesItemOrgSupportWrite, nil
	case "org:replays:read":
		return CreatePrivateRequestScopesItemOrgReplaysRead, nil
	case "org:source_context:read":
		return CreatePrivateRequestScopesItemOrgSourceContextRead, nil
	case "org:integration_settings:read":
		return CreatePrivateRequestScopesItemOrgIntegrationSettingsRead, nil
	case "org:integration_settings:write":
		return CreatePrivateRequestScopesItemOrgIntegrationSettingsWrite, nil
	case "org:workspace_members:read":
		return CreatePrivateRequestScopesItemOrgWorkspaceMembersRead, nil
	case "org:workspace_members:write":
		return CreatePrivateRequestScopesItemOrgWorkspaceMembersWrite, nil
	case "org:workspace_billing:read":
		return CreatePrivateRequestScopesItemOrgWorkspaceBillingRead, nil
	case "org:workspace_billing:write":
		return CreatePrivateRequestScopesItemOrgWorkspaceBillingWrite, nil
	case "org:workspace_basics:read":
		return CreatePrivateRequestScopesItemOrgWorkspaceBasicsRead, nil
	case "org:workspace_basics:write":
		return CreatePrivateRequestScopesItemOrgWorkspaceBasicsWrite, nil
	case "org:workspace_domains:read":
		return CreatePrivateRequestScopesItemOrgWorkspaceDomainsRead, nil
	case "org:workspace_domains:write":
		return CreatePrivateRequestScopesItemOrgWorkspaceDomainsWrite, nil
	case "org:workspace_auth:read":
		return CreatePrivateRequestScopesItemOrgWorkspaceAuthRead, nil
	case "org:workspace_auth:write":
		return CreatePrivateRequestScopesItemOrgWorkspaceAuthWrite, nil
	case "org:workspace:destroy":
		return CreatePrivateRequestScopesItemOrgWorkspaceDestroy, nil
	case "org:workspace:transfer_ownership":
		return CreatePrivateRequestScopesItemOrgWorkspaceTransferOwnership, nil
	case "release:write":
		return CreatePrivateRequestScopesItemReleaseWrite, nil
	case "ingest:write":
		return CreatePrivateRequestScopesItemIngestWrite, nil
	}
	var t CreatePrivateRequestScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePrivateRequestScopesItem) Ptr() *CreatePrivateRequestScopesItem {
	return &c
}
