// Code generated by Fern. DO NOT EDIT.

package keys

import (
	json "encoding/json"
	internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
	big "math/big"
)

var (
	createPublicRequestFieldWorkspaceSlug  = big.NewInt(1 << 0)
	createPublicRequestFieldSurfaceSlug    = big.NewInt(1 << 1)
	createPublicRequestFieldIdempotencyKey = big.NewInt(1 << 2)
	createPublicRequestFieldName           = big.NewInt(1 << 3)
)

type CreatePublicRequest struct {
	WorkspaceSlug  string `json:"-" url:"-"`
	SurfaceSlug    string `json:"-" url:"-"`
	IdempotencyKey string `json:"idempotencyKey" url:"-"`
	Name           string `json:"name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePublicRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePublicRequest) SetWorkspaceSlug(workspaceSlug string) {
	c.WorkspaceSlug = workspaceSlug
	c.require(createPublicRequestFieldWorkspaceSlug)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePublicRequest) SetSurfaceSlug(surfaceSlug string) {
	c.SurfaceSlug = surfaceSlug
	c.require(createPublicRequestFieldSurfaceSlug)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePublicRequest) SetIdempotencyKey(idempotencyKey string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createPublicRequestFieldIdempotencyKey)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePublicRequest) SetName(name string) {
	c.Name = name
	c.require(createPublicRequestFieldName)
}

func (c *CreatePublicRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePublicRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePublicRequest(body)
	return nil
}

func (c *CreatePublicRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePublicRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deletePublicRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	deletePublicRequestFieldSurfaceSlug   = big.NewInt(1 << 1)
	deletePublicRequestFieldPublicKeyID   = big.NewInt(1 << 2)
)

type DeletePublicRequest struct {
	WorkspaceSlug string `json:"-" url:"-"`
	SurfaceSlug   string `json:"-" url:"-"`
	PublicKeyID   string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePublicRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePublicRequest) SetWorkspaceSlug(workspaceSlug string) {
	d.WorkspaceSlug = workspaceSlug
	d.require(deletePublicRequestFieldWorkspaceSlug)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePublicRequest) SetSurfaceSlug(surfaceSlug string) {
	d.SurfaceSlug = surfaceSlug
	d.require(deletePublicRequestFieldSurfaceSlug)
}

// SetPublicKeyID sets the PublicKeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePublicRequest) SetPublicKeyID(publicKeyID string) {
	d.PublicKeyID = publicKeyID
	d.require(deletePublicRequestFieldPublicKeyID)
}

var (
	getPublicRequestFieldWorkspaceSlug = big.NewInt(1 << 0)
	getPublicRequestFieldSurfaceSlug   = big.NewInt(1 << 1)
	getPublicRequestFieldPublicKeyID   = big.NewInt(1 << 2)
)

type GetPublicRequest struct {
	WorkspaceSlug string `json:"-" url:"-"`
	SurfaceSlug   string `json:"-" url:"-"`
	PublicKeyID   string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPublicRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetWorkspaceSlug sets the WorkspaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPublicRequest) SetWorkspaceSlug(workspaceSlug string) {
	g.WorkspaceSlug = workspaceSlug
	g.require(getPublicRequestFieldWorkspaceSlug)
}

// SetSurfaceSlug sets the SurfaceSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPublicRequest) SetSurfaceSlug(surfaceSlug string) {
	g.SurfaceSlug = surfaceSlug
	g.require(getPublicRequestFieldSurfaceSlug)
}

// SetPublicKeyID sets the PublicKeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPublicRequest) SetPublicKeyID(publicKeyID string) {
	g.PublicKeyID = publicKeyID
	g.require(getPublicRequestFieldPublicKeyID)
}
