// Code generated by Fern. DO NOT EDIT.

package integrations

import (
    context "context"

    sdk "github.com/interfere-inc/terraform-provider-interfere/internal/sdk"
    core "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/core"
    internal "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/internal"
    option "github.com/interfere-inc/terraform-provider-interfere/internal/sdk/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// List integration installations to discover provider, connection state and installation identifiers. Pass the workspace slug in the URL and operation arguments inside the JSON body as { args: ... }. Inspect the request schema for required fields and exact identifier formats. This operation is read-only despite using POST. Permission-filtered queries may return an empty result; do not assume that proves the resource does not exist. Only use pagination arguments declared in the schema.
// 
// Example:
// 
// 	request := &sdk.InstallationsIntegrationsRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    Args: &sdk.InstallationsIntegrationsRequestArgs{
// 	        Providers: []sdk.InstallationsIntegrationsRequestArgsProvidersItem{
// 	            sdk.InstallationsIntegrationsRequestArgsProvidersItemGithub,
// 	        },
// 	    },
// 	}
// 	client.Integrations.Installations(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) Installations(
    ctx context.Context,
    request *sdk.InstallationsIntegrationsRequest,
    opts ...option.RequestOption,
) (sdk.QueryIntegrationsInstallationsResponse, error){
    response, err := c.WithRawResponse.Installations(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Link a surface to an integration destination. Inspect the existing installation and mapping first. Pass the workspace slug in the URL and operation arguments inside the JSON body as { args: ... }. Inspect the request schema for required fields and exact identifier formats. This operation writes data under the caller's existing permissions and records its audit event. Do not automatically retry after a timeout; read the affected resource to determine whether the write completed.
// 
// Example:
// 
// 	request := &sdk.LinkSurfaceToDestinationIntegrationsRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    Args: &sdk.LinkSurfaceToDestinationIntegrationsRequestArgs{
// 	        IntegrationID: "integrationId",
// 	        ProjectID: "projectId",
// 	        SurfaceSlug: "surfaceSlug",
// 	    },
// 	}
// 	client.Integrations.LinkSurfaceToDestination(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) LinkSurfaceToDestination(
    ctx context.Context,
    request *sdk.LinkSurfaceToDestinationIntegrationsRequest,
    opts ...option.RequestOption,
) (*sdk.MutationIntegrationsLinkSurfaceToDestinationResponse, error){
    response, err := c.WithRawResponse.LinkSurfaceToDestination(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Link a surface to a repository. Resolve repository and surface IDs from their list queries first. Pass the workspace slug in the URL and operation arguments inside the JSON body as { args: ... }. Inspect the request schema for required fields and exact identifier formats. This operation writes data under the caller's existing permissions and records its audit event. Do not automatically retry after a timeout; read the affected resource to determine whether the write completed.
// 
// Example:
// 
// 	request := &sdk.LinkSurfaceToRepositoryIntegrationsRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    Args: &sdk.LinkSurfaceToRepositoryIntegrationsRequestArgs{
// 	        IntegrationID: "integrationId",
// 	        RepositoryID: "repositoryId",
// 	        SurfaceSlug: "surfaceSlug",
// 	    },
// 	}
// 	client.Integrations.LinkSurfaceToRepository(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) LinkSurfaceToRepository(
    ctx context.Context,
    request *sdk.LinkSurfaceToRepositoryIntegrationsRequest,
    opts ...option.RequestOption,
) (*sdk.MutationIntegrationsLinkSurfaceToRepositoryResponse, error){
    response, err := c.WithRawResponse.LinkSurfaceToRepository(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Remove a surface's destination mapping. This changes integration routing. Pass the workspace slug in the URL and operation arguments inside the JSON body as { args: ... }. Inspect the request schema for required fields and exact identifier formats. This operation writes data under the caller's existing permissions and records its audit event. Do not automatically retry after a timeout; read the affected resource to determine whether the write completed.
// 
// Example:
// 
// 	request := &sdk.UnlinkSurfaceDestinationMappingIntegrationsRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    Args: &sdk.UnlinkSurfaceDestinationMappingIntegrationsRequestArgs{
// 	        SurfaceSlug: "surfaceSlug",
// 	    },
// 	}
// 	client.Integrations.UnlinkSurfaceDestinationMapping(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) UnlinkSurfaceDestinationMapping(
    ctx context.Context,
    request *sdk.UnlinkSurfaceDestinationMappingIntegrationsRequest,
    opts ...option.RequestOption,
) (*sdk.MutationIntegrationsUnlinkSurfaceDestinationMappingResponse, error){
    response, err := c.WithRawResponse.UnlinkSurfaceDestinationMapping(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Remove a surface's integration mapping. Inspect the selected mapping before unlinking it. Pass the workspace slug in the URL and operation arguments inside the JSON body as { args: ... }. Inspect the request schema for required fields and exact identifier formats. This operation writes data under the caller's existing permissions and records its audit event. Do not automatically retry after a timeout; read the affected resource to determine whether the write completed.
// 
// Example:
// 
// 	request := &sdk.UnlinkSurfaceMappingIntegrationsRequest{
// 	    WorkspaceSlug: "workspaceSlug",
// 	    Args: &sdk.UnlinkSurfaceMappingIntegrationsRequestArgs{
// 	        SurfaceSlug: "surfaceSlug",
// 	    },
// 	}
// 	client.Integrations.UnlinkSurfaceMapping(
// 	    context.TODO(),
// 	    request,
// 	)
func (c *Client) UnlinkSurfaceMapping(
    ctx context.Context,
    request *sdk.UnlinkSurfaceMappingIntegrationsRequest,
    opts ...option.RequestOption,
) (*sdk.MutationIntegrationsUnlinkSurfaceMappingResponse, error){
    response, err := c.WithRawResponse.UnlinkSurfaceMapping(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

